### ISSUE TITLE
patreon.com

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#101]
Hello,

Do you have a patreon.com or equivalent.

I've been following the project for three days and you're being very responsive.

You deserve it!

**Comment by n4ze3m** [comment]
Thank you for considering supporting the project! I currently use Ko-fi for donations. You can find my page here: https://ko-fi.com/n4ze3m. Any contribution is greatly appreciated, but please only donate if you truly enjoy the project. Thanks again! ❤️
