### ISSUE TITLE
V.1.0.1==> V1.0.2 Telegram and Discord problem

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#104]
Since last night's update, the bot on Telegram and Discord no longer works.

The "ping" command gives "pong".

The "start" command gives "Hey, How can I assist you?

Then you get: "Opps! Something went wrong".

Thanks for your help

**Comment by n4ze3m** [comment]
Hey, can you give me the logs, please?

**Comment by comeback01** [comment]
Excuse my question, but where are the logs?

**Comment by n4ze3m** [comment]
It's ok :)

Are you using it locally or on Railway.app?

If you are using it locally with Docker, then run `docker-compose logs dialqobase`.

logs on docker terminal:
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/652f9eb5-1005-4f38-97d7-c4fcb43da624)


If you are using it on Railway, go to the project, click on 'dialoqbase-server,' and it will open a sidebar where, under deployments tags, you can view the logs by clicking 'View logs'

logs on railway:
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/7815450c-7e16-4a2d-9980-c5b90011a142)

**Comment by comeback01** [comment]
docker-compose logs dialoqbase
![Capture d'écran 2023-10-05 160737](https://github.com/n4ze3m/dialoqbase/assets/17897116/d428b2fc-1622-441e-aee3-5bd28178506e)

**Comment by n4ze3m** [comment]
Can you send a message to your connected Telegram bot and check the logs? Sorry for the issue causing problems with the integration now.

**Comment by comeback01** [comment]
No thanks for your help, this weekend I'm planning a monthly payme
![Capture d'écran 2023-10-05 160737](https://github.com/n4ze3m/dialoqbase/assets/17897116/cf6d92a8-d0ec-4406-a41e-7744f1001eb3)
nt.

**Comment by comeback01** [comment]
No thanks for your help, this weekend I'm planning a monthly payment. 


![Capture d'écran 2023-10s05 161341](https://github.com/n4ze3m/dialoqbase/assets/17897116/2bc4c50f-7b19-4f57-896c-a9bdb1e4e26c)

**Comment by comeback01** [comment]
No, I'm using the free version. I didn't see how to get a paid version, and what's the price?

**Comment by n4ze3m** [comment]
Can you run anything on their playground at https://app.fireworks.ai/models/fireworks/mistral-7b-instruct-4k ?

Fireworks pricing page: https://readme.fireworks.ai/page/pricing

You can add credit to your fireworks account https://app.fireworks.ai/users?tab=billing

**Comment by comeback01** [comment]
If I pay, won't there be a problem with telegram and discord?

I'll have to check if the prices are right. 
![Capture d'écran 2023-10-05 163113](https://github.com/n4ze3m/dialoqbase/assets/17897116/b524f369-8573-4fe2-a530-250a125b9a6f)

**Comment by comeback01** [comment]
I tried with the openAI api, it works.

Then I put back the fireworks.ai api (LLMA 2 70B), and it works again.

Maybe something to do with the update?
![Capture d'écran 2023-10-05 171321](https://github.com/n4ze3m/dialoqbase/assets/17897116/5f326c39-4c36-48a1-9791-2e3ed3037b21)

**Comment by n4ze3m** [comment]
Ah, it may be because of the Fireworks API being down or some issue at that time. I tried to reproduce the error locally, but I'm not encountering it. If I do encounter it, I will release a patch :). I will also add error logging to the dialoqbase integration tabs in an upcoming update, making it easier to debug

**Comment by comeback01** [comment]
I still have a problem with the Bot discord and Telegram.

After a few hours, I get the same message as yesterday.

All I have to do is switch from Fireworks to GPT, then put Fireworks back on, and it works.

It's as if the connection had been cut and this operation reactivates the connection.

**Comment by n4ze3m** [comment]
Interesting. I will look into how to fix the API connection problem.
