### ISSUE TITLE
Can someone help me look at this problem

### ISSUE THREAD

**Issue by 31702160226** [n4ze3m/dialoqbase#108]
When I started the project login account, I kept throwing exceptions when I entered the Get my robot page. I checked the http call interface and the result was {
"statusCode": 401,
"code": "FST_JWT_AUTHORIZATION_TOKEN_INVALID",
"error": "Unauthorized",
"message": "Authorization token is invalid: The token signature is invalid."
I have checked redis, dialoqbase and Dialoqbase-Postgres and there are no error logs. May I ask why we can use all of them normally before October

**Comment by n4ze3m** [comment]
Hey, are you using it locally, right? The `FST_JWT_AUTHORIZATION_TOKEN_INVALID` token is not valid. You can log out and log in once more or try in incognito mode.

**Comment by 31702160226** [comment]
> Hey, are you using it locally, right? The `FST_JWT_AUTHORIZATION_TOKEN_INVALID` jwt token is not valid. You can log out and log in once more or try in incognito mode.

Following your advice, I logged out of the account and logged in again. Thank you！！！

**Comment by n4ze3m** [comment]
Is it work?

**Comment by 31702160226** [comment]
> Is it work?

yes, It's working properly again！
