### ISSUE TITLE
Who can help me look at this problem, thank you

### ISSUE THREAD

**Issue by 31702160226** [n4ze3m/dialoqbase#110]
Following the tutorial I pulled up the code from git to my computer, edited the.env file and filled it with OPENAI_API_KEY and DB_SECRET_KEY, and then started the project with docker-compose up -d to create a bot, but when I sent a message to the bot, The http request result returned an error, as follows

{
    "statusCode": 500,
    "code": "P2010",
    "error": "Internal Server Error",
    "message": "\nInvalid `prisma.$queryRaw()` invocation:\n\n\nRaw query failed. Code: `54000`. Message: `ERROR: vector cannot have more than 1024 dimensions`"
}

What should I do in this situation? Did I fill in the wrong configuration?I have tried to log in again by logging out of the account, deleting the container in docker and the three directories of.postgres,.redis, and.uploads in the docker directory of the project, and then using docker-compose up -d command to start the project

**Comment by n4ze3m** [comment]
Hey, sorry for the issue. It looks like an embedding issue. Which model did you use, OpenAI or other models? Also, can you clone the project once more in a different directory and start again?

**Comment by 31702160226** [comment]
> Hey, sorry for the issue. It looks like an embedding issue. Which model did you use, OpenAI or other models? Also, can you clone the project once more in a different directory and start again?
Using the openai model, my previous openai key quota was used up, and then I replaced another openai key. After successfully creating the robot and feeding the data, I launched a chat with the robot and threw this exception

**Comment by n4ze3m** [comment]
Are you using the latest version? Can you create another bot to see if the error is still coming
