### ISSUE TITLE
Railway Template - 6 Required Inputs but docs say only Supabase+OpenAI needed 

### ISSUE THREAD

**Issue by skwaugh** [n4ze3m/dialoqbase#112]
I'm trying to use the Railway template.  The docs here say that only two inputs are required for the initial deployment: a Supabase URL and an OpenAI key.

Instead, the following are required:
DATABASE_URL (Supabase)
OPENAI_API_KEY
GITHUB_ACCESS_TOKEN
FIREWORKS_API_KEY
ELEVENLABS_API_KEY
GOOGLE_API_KEY

It's not clear why these other API providers are required upfront, nor why dialoqbase requires a personal access token for my github account.

Can you either update the docs to reflect these additional requirements, or adjust the railway template to align with the docs?  I'm looking forward to using the project

<img width="536" alt="tools Railway 2023-10-12 at 3 27 27 PM" src="https://github.com/n4ze3m/dialoqbase/assets/4550411/b6b33ff7-e295-4603-8591-a037c9a8ea56">

**Comment by n4ze3m** [comment]
Hey, sorry about that. I will update the template right now.

**Comment by n4ze3m** [comment]
Hey, the template has been updated

**Comment by skwaugh** [comment]
That was fast.  Thank you!  Building & deploying now
