### ISSUE TITLE
Railway deployment dont work it  keeps crashing also docker deployed in mac isnt working 

### ISSUE THREAD

**Issue by OpinionAI** [n4ze3m/dialoqbase#114]
Railway deployment dont work it  keeps crashing also docker deployed in mac isnt working

**Comment by n4ze3m** [comment]
Hey, can you show me the railway logs? I tested Docker on both Windows and Linux machines, and it worked fine. I don't know what happened with Mac; I will look into it.

**Comment by n4ze3m** [comment]
>  got any updates on mac deployment.

Yeah, I will publish an AMD and ARM-based image so that it works on Mac (I guess)

> Also I want to discuss something as we want the use the Dialoqbase as backend to an app we are building with tweaked frontend would you be willing  to assist us.

I'm sorry :( Are you looking for a chatbot API for a custom frontend?

**Comment by n4ze3m** [comment]
Hey the latest Docker image supports ARM64, which works on Mac.
