### ISSUE TITLE
Data Hallucination Issue with Crawler on JavaScript and CSS-heavy Websites

### ISSUE THREAD

**Issue by Sad-Machin3** [n4ze3m/dialoqbase#116]
### **Issue Description:**
I've encountered an issue with data hallucination when using a web crawler on websites with a substantial amount of JavaScript and CSS. The crawler, specifically the CheerioWebBaseLoader, seems to be producing inaccurate or incomplete data due to the dynamic nature of these websites.

**Steps to Reproduce:**

1. Select Crawler as Data Source.
2. Choose a website with a large amount of JavaScript and CSS, for example, (https://www.ipangram.com/).
3. Let the bot cook and ask any questions regarding to the website.

**Expected Behavior:**
The llm should answer expected answers related to website.

**Actual Behavior:** 
The llm appears to be producing inaccurate answers. 

**Environment:**
Operating System: Windows 10
Embeddings: Huggingface
ChatModel: Fireworks (llama-v2-7b-chat)

**Screenshots:**
This is the chunks generated by Document Loader

![image](https://github.com/n4ze3m/dialoqbase/assets/114864715/54d3d36d-eef2-42c7-b1d7-8fa2ed5f857d)

**Comment by n4ze3m** [comment]
I will look into it! Thanks for reporting it

**Comment by Sad-Machin3** [comment]
Is there any update @n4ze3m ?

**Comment by n4ze3m** [comment]
fix will be released in this week's update

**Comment by Sad-Machin3** [comment]
Is this issue resolved @n4ze3m ?? 👀

**Comment by n4ze3m** [comment]
Hey, I tried using `html-to-text`, but it didn't work as expected. I'm now trying to find a better solution

**Comment by n4ze3m** [comment]
Fix has been released; please feel free to reopen this issue if the problem persists
