### ISSUE TITLE
[features] add OpenRouter support for language and embedding models

### ISSUE THREAD

**Issue by fuegovic** [n4ze3m/dialoqbase#120]
[OpenRouter](https://openrouter.ai/docs#models) is offering all models with easily configurable limits. It would be great to see it added to the list supported LLMs providers
 
It is compatible with the [OpenAI Chat API](https://openrouter.ai/docs#format)

**Comment by n4ze3m** [comment]
Wow, this is so nice! I will look into adding it in the upcoming update

**Comment by n4ze3m** [comment]
Hey! Version 1.3.0 has been released, which allows you to easily add OpenRouter models. Simply go to Settings > Model > Add New Model.

Base URL: https://openrouter.ai/api/v1
API Key: OpenRouter API key

Select the model you want to add. 

Please note that currently, we only support chat models

**Comment by brinrbc** [comment]
> Hey! v1.3.0 has been released, which allows you to easily add OpenRouter models. Simply go to Settings > Model > Add New Model.
> 
> Base URL: https://openrouter.ai/api/v1 API Key: OpenRouter API key
> 
> Select the model you want to add.
> 
> Please note that currently, we only support chat models

Could you please tell me if you have removed the Add Model function? I can't find it in the settings
