### ISSUE TITLE
It would be really nice to have an eternal memory in chatbots from LLM ( RAG )

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#122]
It would be really nice to have an eternal memory in chatbots from LLM ( RAG ) https://github.com/cpacker/MemGPT
Can anyone help with this?  I would do it myself - but don't know enough programming language.

A very necessary and useful feature - see review and description.
https://www.youtube.com/watch?v=QQ2QOPWZKVc
In this video, we look at MemGPT - a new way to give AI unlimited memory/context windows by breaking the context size constraint.

Integrate into dialogbase please if possible! + 10000 points to karma!  Thanks for your project, it is very interesting and useful. It is the best one on github!

**Comment by n4ze3m** [comment]
I will look into it. I'll comment here when it's ready :)

**Comment by ferstpetr777** [comment]
Nazeem, Could you please tell me if you were able to test it?

**Comment by n4ze3m** [comment]
> Nazeem, Could you please tell me if you were able to test it?

Unfortunately, not, but the existing rag has been improved and is better now. It will be released as version 1.4.0 this week
