### ISSUE TITLE
how to set the openai apiBase parameter?

### ISSUE THREAD

**Issue by pullitdown** [n4ze3m/dialoqbase#126]
when i loacl installing , cause i use the openai proxy service key ,i need setting the api_base like the code below ,how can i set it in this repositories?
`import os
import openai
openai.api_key = 'sk-pxxxxxxxxxxxxxxxxxxx53'
openai.api_base = 'https://key.xxxx.ai/v1'
chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])

print(completion.choices[0].message)
`

**Comment by n4ze3m** [comment]
Currently, there is no way to pass a proxy URL. I will release a patch today.

**Comment by n4ze3m** [comment]
You can load a custom model via the admin settings. Put your API key in the environment `OPENAI_API_KEY` and 

go to Settings > Models > Add New Model > Add OpenAI proxy URL > select your preferred model

**Comment by pullitdown** [comment]
thanks for your answer. i try add new model follow the example but not work ,and error log "Unable to fetch model. Inputed url is not openai api compatible".

**Comment by pullitdown** [comment]
> You can load a custom model via the admin settings. Put your API key in the environment `OPENAI_API_KEY` and
> 
> go to Settings > Models > Add New Model > Add OpenAI proxy URL > select your preferred model
> 
> Please let me know if it works.
> 
> example: https://twitter.com/dialoqbase/status/1715385952468877770

thanks for your answer. i try add new model follow the example but not work ,and error log "Unable to fetch model. Inputed url is not openai api compatible".

**Comment by pullitdown** [comment]
by the way, i found a little bug , adding github url  when i create bot , the url with symbol like '_' would be told "Please enter a valid public github repo URL"

**Comment by n4ze3m** [comment]
> thanks for your answer. i try add new model follow the example but not work ,and error log "Unable to fetch model. Inputed url is not openai api compatible".

It's okay; I'm releasing a new update this Friday, which will allow you to put the OpenAI proxy base URL in the `.env`

> by the way, i found a little bug , adding github url when i create bot , the url with symbol like '_' would be told "Please enter a valid public github repo URL"

Thankss need to update my GitHub regex 😅

**Comment by n4ze3m** [comment]
Hey you can now configure a custom API base URL by adding `OPENAI_API_URL`  with your URL
