### ISSUE TITLE
will the "Hybrid Search Retrieval" search mode work in the chatbot on the webpage?

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#127]
Greetings, I have a question - will the "Hybrid Search Retrieval" search mode work in the chatbot on the webpage? In the note settings it says it only works on the playground.

**Comment by n4ze3m** [comment]
Yes, the hybrid search retrieval is in beta mode and is currently available in the playground. It will be available in upcoming updates for all integrations, alongside RAG support. We are currently taking feedback about it.

**Comment by ferstpetr777** [comment]
Works great, in sum with RAG gives a very decent result, this is the best that I have seen from libraries on git, tried all paid services on this topic - the result they have worse.

**Comment by ferstpetr777** [comment]
Thank you, your product is the best!

**Comment by n4ze3m** [comment]
Hey, Hybrid Search Retrieval & RAG is now supported on web embedding
