### ISSUE TITLE
Can you please tell me how to automatically transfer bot templates

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#130]
I have a question: Can you please tell me how to automatically transfer bot templates made under the administrator account to users who have registered again? So that they do not go to an empty interface, but with ready-made templates.

Colleagues, the second question, is it possible to calculate the number of tokens for registered users, how to monitor their activity and statistics on the use of bots ?

Thank you for your prompt and creative response :-).....

**Comment by n4ze3m** [comment]
> I have a question: Can you please tell me how to automatically transfer bot templates made under the administrator account to users who have registered again? So that they do not go to an empty interface, but with ready-made templates.

I think a PostgreSQL trigger could be useful

**Comment by ferstpetr777** [comment]
Thank you! it remains to understand how to do it )))))... maybe there is a link to instructions ? I will be extremely grateful for a hint and +10000 to karma wish!
