### ISSUE TITLE
Error : Integrating with Local AI

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#131]
Tried to Integrate with the suggested **LocalAI** , and **LM Studio** but neither worked .
Noting that i tried many links ,  /v1 , /v1/chat/ . /v1/chat/completions ... etc 

screenshots attached 
![Local AI 2](https://github.com/n4ze3m/dialoqbase/assets/81163928/4420ee72-dad9-4e8c-8fdb-0810c01089da)
![Local AI](https://github.com/n4ze3m/dialoqbase/assets/81163928/ae4990c7-3b93-4910-9b05-137035c440ad)

![LM Studio](https://github.com/n4ze3m/dialoqbase/assets/81163928/de5caea0-7b4e-4323-aed0-8fab147d82cb)

**Comment by n4ze3m** [comment]
Hey, the issue is that localhost:8080 on your system cannot be called inside a Docker container, which is why it's throwing an error.

You can learn more about it here: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by n4ze3m** [comment]
try `http://host.docker.internal:8080/v1` or `http://host.docker.internal:1234/v1`
