### ISSUE TITLE
Error - Local Embedding 

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#132]
Logs below ,  i tried all local embedding models , noting that openai embedding works fine .

[+] Running 3/0
 ✔ Container redis                Running                                                                                                                                              0.0s
 ✔ Container dialoqbase-postgres  Running                                                                                                                                              0.0s
 ✔ Container dialoqbase           Running                                                                                                                                              0.0s
Attaching to dialoqbase, dialoqbase-postgres, redis
dialoqbase           | [info] use ffmpeg.wasm v0.12.0
dialoqbase           | Processing queue
dialoqbase           | loading txt
dialoqbase           | TypeError: fetch failed
dialoqbase           |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
dialoqbase           |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at runNextTicks (node:internal/process/task_queues:64:3)
dialoqbase           |     at process.processImmediate (node:internal/timers:447:9)
dialoqbase           |     at async getModelFile (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
dialoqbase           |     at async getModelJSON (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
dialoqbase           |     at async Promise.all (index 0)
dialoqbase           |     at async loadTokenizer (file:///app/node_modules/@xenova/transformers/src/tokenizers.js:52:16)
dialoqbase           |     at async AutoTokenizer.from_pretrained (file:///app/node_modules/@xenova/transformers/src/tokenizers.js:3824:48)
dialoqbase           |     at async Promise.all (index 0) {
dialoqbase           |   cause: _ConnectTimeoutError: Connect Timeout Error
dialoqbase           |       at onConnectTimeout (node:internal/deps/undici/undici:6616:28)
dialoqbase           |       at node:internal/deps/undici/undici:6574:50
dialoqbase           |       at Immediate._onImmediate (node:internal/deps/undici/undici:6605:13)
dialoqbase           |       at process.processImmediate (node:internal/timers:476:21) {
dialoqbase           |     code: 'UND_ERR_CONNECT_TIMEOUT'
dialoqbase           |   }
dialoqbase           | }
dialoqbase           | Processing queue
dialoqbase           | loading txt
redis                | 1:M 30 Oct 2023 08:29:25.319 * 100 changes in 300 seconds. Saving...
redis                | 1:M 30 Oct 2023 08:29:25.320 * Background saving started by pid 20
redis                | 20:C 30 Oct 2023 08:29:25.323 * DB saved on disk
redis                | 20:C 30 Oct 2023 08:29:25.323 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis                | 1:M 30 Oct 2023 08:29:25.420 * Background saving terminated with success
dialoqbase           | TypeError: fetch failed
dialoqbase           |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at async getModelFile (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
dialoqbase           |     at async constructSession (file:///app/node_modules/@xenova/transformers/src/models.js:119:18)
dialoqbase           |     at async Promise.all (index 1)
dialoqbase           |     at async BertModel.from_pretrained (file:///app/node_modules/@xenova/transformers/src/models.js:713:20)
dialoqbase           |     at async AutoModel.from_pretrained (file:///app/node_modules/@xenova/transformers/src/models.js:3767:20)
dialoqbase           |     at async Promise.all (index 1)
dialoqbase           |     at async loadItems (file:///app/node_modules/@xenova/transformers/src/pipelines.js:2305:5)
dialoqbase           |     at async pipeline (file:///app/node_modules/@xenova/transformers/src/pipelines.js:2251:19) {
dialoqbase           |   cause: Error: Client network socket disconnected before secure TLS connection was established
dialoqbase           |       at connResetException (node:internal/errors:720:14)
dialoqbase           |       at TLSSocket.onConnectEnd (node:_tls_wrap:1655:19)
dialoqbase           |       at TLSSocket.emit (node:events:529:35)
dialoqbase           |       at endReadableNT (node:internal/streams/readable:1368:12)
dialoqbase           |       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
dialoqbase           |     code: 'ECONNRESET',
dialoqbase           |     path: undefined,
dialoqbase           |     host: 'huggingface.co',
dialoqbase           |     port: 443,
dialoqbase           |     localAddress: null
dialoqbase           |   }
dialoqbase           | }
dialoqbase-postgres  | 2023-10-30 08:30:15.393 UTC [27] LOG:  checkpoint starting: time
dialoqbase-postgres  | 2023-10-30 08:30:17.709 UTC [27] LOG:  checkpoint complete: wrote 24 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.306 s, sync=0.006 s, total=2.316 s; sync files=20, longest=0.002 s, average=0.001 s; distance=14 kB, estimate=14 kB
dialoqbase           | Processing queue
dialoqbase           | loading txt
dialoqbase           | TypeError: fetch failed
dialoqbase           |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
dialoqbase           |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at runNextTicks (node:internal/process/task_queues:64:3)
dialoqbase           |     at process.processImmediate (node:internal/timers:447:9)
dialoqbase           |     at async getModelFile (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
dialoqbase           |     at async constructSession (file:///app/node_modules/@xenova/transformers/src/models.js:119:18)
dialoqbase           |     at async Promise.all (index 1)
dialoqbase           |     at async BertModel.from_pretrained (file:///app/node_modules/@xenova/transformers/src/models.js:713:20)
dialoqbase           |     at async AutoModel.from_pretrained (file:///app/node_modules/@xenova/transformers/src/models.js:3767:20)
dialoqbase           |     at async Promise.all (index 1) {
dialoqbase           |   cause: _ConnectTimeoutError: Connect Timeout Error
dialoqbase           |       at onConnectTimeout (node:internal/deps/undici/undici:6616:28)
dialoqbase           |       at node:internal/deps/undici/undici:6574:50
dialoqbase           |       at Immediate._onImmediate (node:internal/deps/undici/undici:6605:13)
dialoqbase           |       at process.processImmediate (node:internal/timers:476:21) {
dialoqbase           |     code: 'UND_ERR_CONNECT_TIMEOUT'
dialoqbase           |   }
dialoqbase           | }
dialoqbase           | Processing queue
dialoqbase           | loading txt
dialoqbase           | TypeError: fetch failed
dialoqbase           |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
dialoqbase           |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at runNextTicks (node:internal/process/task_queues:64:3)
dialoqbase           |     at process.processImmediate (node:internal/timers:447:9)
dialoqbase           |     at async getModelFile (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
dialoqbase           |     at async getModelJSON (file:///app/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
dialoqbase           |     at async Promise.all (index 1)
dialoqbase           |     at async loadTokenizer (file:///app/node_modules/@xenova/transformers/src/tokenizers.js:52:16)
dialoqbase           |     at async AutoTokenizer.from_pretrained (file:///app/node_modules/@xenova/transformers/src/tokenizers.js:3824:48)
dialoqbase           |     at async Promise.all (index 0) {
dialoqbase           |   cause: _ConnectTimeoutError: Connect Timeout Error
dialoqbase           |       at onConnectTimeout (node:internal/deps/undici/undici:6616:28)
dialoqbase           |       at node:internal/deps/undici/undici:6574:50
dialoqbase           |       at Immediate._onImmediate (node:internal/deps/undici/undici:6605:13)
dialoqbase           |       at process.processImmediate (node:internal/timers:476:21) {
dialoqbase           |     code: 'UND_ERR_CONNECT_TIMEOUT'
dialoqbase           |   }
dialoqbase           | }
dialoqbase           | Processing queue
dialoqbase           | loading txt
dialoqbase           | TypeError: fetch failed
dialoqbase           |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at async Promise.all (index 5) {
dialoqbase           |   cause: _ConnectTimeoutError: Connect Timeout Error
dialoqbase           |       at onConnectTimeout (node:internal/deps/undici/undici:6616:28)
dialoqbase           |       at node:internal/deps/undici/undici:6574:50
dialoqbase           |       at Immediate._onImmediate (node:internal/deps/undici/undici:6605:13)
dialoqbase           |       at process.processImmediate (node:internal/timers:476:21) {
dialoqbase           |     code: 'UND_ERR_CONNECT_TIMEOUT'
dialoqbase           |   }
dialoqbase           | }

**Comment by n4ze3m** [comment]
I will look into what happened
