### ISSUE TITLE
Conversations do not feel natural

### ISSUE THREAD

**Issue by wbdsnbraun** [n4ze3m/dialoqbase#133]
When writing with the bot, the first question usually gets answered quite well based on the provided information. When continuing the conversation or for example thanking the bot for the provided answer, the next answer just uses the previous question as input. This leads to really weird conversations the more chat history is present. Is this the desired behaviour? Is there an easy solution to switch between question answering based on the information provided and authentic answers like ChatGpt?

Here is an example:
![Example](https://github.com/n4ze3m/dialoqbase/assets/145428653/75a3744a-8615-40b1-b051-54f83812cd9a)

**Comment by n4ze3m** [comment]
Hey, yeah, that's a big issue when using 'Conversational Chain' or 'RAG.' I will look into it. One solution is updating the system prompt, which has a 50% chance of working.

**Comment by phpia** [comment]
Hey, in this line. Could you please add more info from the next concepts or better practice in dialoqbase?

RAG, Its used for recovery previous conversation?
{context}
{question}
{chat_history}
Question Answering Prompt (System Prompt)
Question Generator Prompt 

Thanks!

**Comment by n4ze3m** [comment]
I've been a little busy with work recently. I will release an update where users can configure custom responses for messages 👀

**Comment by n4ze3m** [comment]
This issue has been resolved and will be released in the next update ;)

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/69c3d9e3-68f7-4557-83f2-38cc3803de93)

**Comment by n4ze3m** [comment]
Fix has been released; please feel free to reopen this issue if the problem persists
