### ISSUE TITLE
v1.3.0 bug docker and Railway

### ISSUE THREAD

**Issue by chalitgubkb** [n4ze3m/dialoqbase#136]
@n4ze3m 
docker 

![image](https://github.com/n4ze3m/dialoqbase/assets/43214912/840e2b42-8f5b-4abe-86c9-2b5256af9cf0)
![image](https://github.com/n4ze3m/dialoqbase/assets/43214912/3794ac71-8ac3-4076-92fc-65fdf597f3df)

Railway
![image](https://github.com/n4ze3m/dialoqbase/assets/43214912/2504743d-4f0b-4579-aaee-c29ced9d095c)

**Comment by n4ze3m** [comment]
Hey, there was an issue with naming the migration file. I'm releasing a patch now. I will comment here when it's done.

**Comment by n4ze3m** [comment]
Hey, patch as been released

**Comment by ferstpetr777** [comment]
Yes, when installing a new installation on the server, from scratch, when installing from the docker - you get this error. but if you update from the docker, from an already installed version, this error will not occur.
In general, now, anyone who first downloaded and will install will not be able to install.
