### ISSUE TITLE
One Click Deploy Vercel

### ISSUE THREAD

**Issue by walter-grace** [n4ze3m/dialoqbase#14]
Could you add a feature to deploy this feature easier?

What is the best way to deploy this code

**Comment by n4ze3m** [comment]
> Could you add a feature to deploy this feature easier?
> 
> What is the best way to deploy this code

good question, I don't think Vercel supports Fastify server, but I'm creating a railway.app template for one-click deployment.

**Comment by n4ze3m** [comment]
One-click deployment to railway.app using Supabase as the database (Railway's Postgres does not support pg_vector).

[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/TXdjD7?referralCode=olbszX)
