### ISSUE TITLE
Streaming function has stopped working

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#140]
Good day. please take a look - but it seems that the Streaming function has stopped working, the message is displayed at once and with a delay. it's important for chat users to see the answer. Thank you for your prompt reply.

**Comment by n4ze3m** [comment]
Hey, can you check the logs? I think it's because of OpenAI or the provider you use.

**Comment by ferstpetr777** [comment]
The logs do not show errors, but the answer in the chat goes without streaming. by the way there was an update of the chat, please tell me how to make it so that new AI models were available in the service dialog base ? https://openai.com/blog/new-models-and-developer-products-announced-at-devday

**Comment by n4ze3m** [comment]
New models soon available on the application.

**Comment by oalmajalists** [comment]
hello , 
i am using openai API , but the answer streaming has stopped , noting its enabled from UI and no related logs .
please help
