### ISSUE TITLE
 Bot does not save message changes

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#143]
Nazeem, in the Appearance section of the chatbot settings, in the "Welcome message" field, the bot does not save message changes - when you first access the chat. always responds with only one phrase - " Hey, How can I help you?" . I tested the bot connected to Telegram.

**Comment by n4ze3m** [comment]
This is because bot customization is not connected with integrations. I will add that fix in this update

**Comment by n4ze3m** [comment]
Fix has been released; please feel free to reopen this issue if the problem persists

**Comment by ferstpetr777** [comment]
+10000 karma points, respect!
