### ISSUE TITLE
LM Studio - Integration Error 

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#146]
I get this error when i try to add LM Studio hosted API : 

-Dialoqbase  Error : "Cannot read properties of undefined (reading 'map') ".

-LM Studio Log : 
[2023-11-12 11:36:53.608] [ERROR] Unexpected endpoint or method. (GET /v1//models). Returning 200 anyway.

**Comment by n4ze3m** [comment]
You added an extra `/`, I guess, according to the logs.

 Try removing it; instead of 
`{your-host}/v1/`

 use 

`{your-host}/v1`
