### ISSUE TITLE
Issue while creating text bot 

### ISSUE THREAD

**Issue by tejasg910** [n4ze3m/dialoqbase#149]
Hello, 

I was trying to make text bots locally on version 1.4.1,  but was not able to process and give proper information about the provided text, 
as the data source shows pending initially, later on, it shows "failed". 

system details: 
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

MODELS 
Chat model: GPT 3.5 turbo (openai)
Embedding model: text embedding ada 002 

Database: supabase

**Comment by n4ze3m** [comment]
Hello, do you have any logs? Also, is your Redis functioning correctly?

**Comment by tejasg910** [comment]
working now
