### ISSUE TITLE
when communicating with chat bot in telegram, this error comes out, probably need to reload the chat history automatically, so that there is no error, please help me   error of exceeding the limit in telegram 

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#156]
Nazeem ,  when communicating with chat bot in telegram, this error comes out, probably need to reload the chat history automatically, so that there is no error, please help me 

BadRequestError: 400 This model's maximum context length is 16385 tokens. However, your messages resulted in 16589 tokens. Please reduce the length of the messages.

<img width="927" alt="Снимок экрана 2023-11-26 в 13 07 53" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/99f4ba58-09b0-4b3b-8eae-b7230bf2bb29">

**Comment by n4ze3m** [comment]
The error is likely due to the long duration of the chat; it seems the chat history cannot fit. I will look into a solution

**Comment by ferstpetr777** [comment]
thank you! The chat is short. the error is not stable. sometimes it is there or not. sometimes telegram itself receives this message without calling the chat.

**Comment by n4ze3m** [comment]
I will add a fix in the coming updates
