### ISSUE TITLE
Use Hybrid Search Retrieval

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#157]
Nazeem, can you clarify if "Use Hybrid Search Retrieval" only functions on the playground UI? Does it not work on Telegram or the website?

**Comment by n4ze3m** [comment]
It is available for all integrations

**Comment by ferstpetr777** [comment]
Got it, thanks. But for some reason, when testing, the answers are different on the playground and in telegram. The settings are not changed. The questions are the same.

**Comment by n4ze3m** [comment]
Interesting, I will check
