### ISSUE TITLE
The input text resulted in an error when processed.

### ISSUE THREAD

**Issue by billlilililili** [n4ze3m/dialoqbase#161]
The input text resulted in an error when processed.
![1701339034392](https://github.com/n4ze3m/dialoqbase/assets/46810627/f50da34a-b098-458b-b98d-d938def702e3)

**Comment by n4ze3m** [comment]
Hey, can you check the logs?

**Comment by billlilililili** [comment]
> Hey, can you check the logs?

The error logs can be found in which location? I can't locate the specific position.

**Comment by n4ze3m** [comment]
Hey, send a message to the application. If any errors occur, they will be displayed in your terminal or on the platform you are using, as shown in the latest logs.

**Comment by billlilililili** [comment]
> Hey, send a message to the application. If any errors occur, they will be displayed in your terminal or on the platform you are using, as shown in the latest logs.

![sss](https://github.com/n4ze3m/dialoqbase/assets/46810627/c7d442e7-882d-4cc9-b051-335b376a2f30)

**Comment by n4ze3m** [comment]
Hey, sorry for the late reply. Are you using the application via Docker or Railway? I think the LLM you used might be throwing an error. Are you using OpenAI? If so, make sure the provided API key is working
