### ISSUE TITLE
change administrator login and password

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#162]
Nazeeem , I changed it in the service and didn't save it and now I can't log in. please tell me, where in the code, in what place can I change administrator login and password ?

**Comment by n4ze3m** [comment]
Go to postgres db: Select the 'User' table -> Find the admin user -> Edit and give a default password ('$2a$12$zY2slOG8LUQwzAkMQcooM.UVr0ArR/P0xD.8tyLIMs7Gevx5xHUI6').

**Comment by n4ze3m** [comment]
If you are using the application without Docker, then go to the server, hit 'yarn prisma studio', which opens a query studio. Select the 'User' table, edit the admin user, and provide the default password hash

**Comment by ferstpetr777** [comment]
Thank you very much ! already found it, changed it ).... . Thank you for your help!
