### ISSUE TITLE
Access token for github datasource

### ISSUE THREAD

**Issue by phpia** [n4ze3m/dialoqbase#164]
Hi, Im trying to connect a datasource to a private github repo.

Should I use Fine-grained personal access token or Classical token?

Im not able to connect

Thanks!

**Comment by n4ze3m** [comment]
Hey,

Just put Fine-grained GitHub token into `GITHUB_ACCESS_TOKEN`, but make sure you have granted repo permissions to the generated token; otherwise, it won't work

Also, make sure to check the 'Is private' option on the Dialoqbase datasource form.

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/3ac910e8-f513-4b1d-819a-907ecd457b45)

**Comment by phpia** [comment]
Hi Nazeem, I try with the classic one but the source show pending and if a change of screen appears "Bot is cooking...
It may take some time"

Log shows:
[App] Cloning into './uploads/xxxxx-main'...                                                    │./.git/logs/refs/remotes
Username for 'https://github.com': [App] [info] use ffmpeg.wasm v0.12.0   

thanks!

**Comment by phpia** [comment]
Mmm, in the log is asking for github user maybe not using the token ?

[]([App] Cloning into './uploads/XXXXX.git-main'...
Username for 'https://github.com':)

**Comment by n4ze3m** [comment]
Hey, you have to set 'enable private repo' to true; otherwise, it won't use the token. In a future release, I will fix this issue

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/77ae90de-f088-40bb-ab75-4bc2db64cf13)

**Comment by n4ze3m** [comment]
small example cloning private by enabling 'private repo'


https://github.com/n4ze3m/dialoqbase/assets/39720973/fbcc3f15-0813-4f5e-aa59-a38dafc44227

**Comment by phpia** [comment]
Yes I got it. Its working

Thanks a lot for your help!!!

**Comment by n4ze3m** [comment]
Amazing! I'm closing this issue. Feel free to reopen it if you have any concerns :)
