### ISSUE TITLE
bot activity statistics

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#165]
Nazeem, Hi.  there is a question, what tables in the database to look at to keep track of each bot token consumption. This is necessary in order to make an admin panel for the user. Each new bot will automatically report the volume of token consumption in a visual graph. Maybe there is a ready solution that can be installed ?  

Help me, please!

Here's a sample statistic https://cloud.dify.ai/
<img width="1440" alt="Снимок экрана 2023-12-05 в 11 26 31" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/438b5823-487d-4794-9938-cecd5a6c9f63">

**Comment by n4ze3m** [comment]
Great idea! Will add it in a future release

**Comment by ferstpetr777** [comment]
Nazeem Respect!  When you prepare the release, if possible, add an API function to allow the administrator to manage the bot based on statistics. For example, to open and close the bot if it is paid or not.

**Comment by ferstpetr777** [comment]
Nazeem, please tell me when it will be possible to release a new release of the program ?

**Comment by ferstpetr777** [comment]
Thank you, really looking forward to this! You are the best developer on git for chatbot development! That's not flattery! It's a statement of fact !:)

**Comment by ferstpetr777** [comment]
Hi Nazim, please suggest a method or library, framework format or library on git that can be used to implement in the personal profile of the service dalogbase user statistics of chat bots, statistics of traffic usage of chat bots, and the ability to accept payments for a given traffic. Thank you very much in advance!
