### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by longneck84** [n4ze3m/dialoqbase#166]
if i use api as data source, is it possible to re-fetch it every period of time?

**Comment by longneck84** [comment]
one more question,

is it possible to change the base url for openai api?

**Comment by n4ze3m** [comment]
yes

**Comment by n4ze3m** [comment]
Hey, Dialoqbase API and SDK are now released.

Go to Settings > Profile > Create API Key, then use it as the Authorization key.

You can access Swagger docs by visiting {your_dialoqbase_url}/docs.

SDK Documentation (not fully completed): https://dialoqbase.n4ze3m.com/reference/getting-started.html

If you face any issue, please join Dialoqbase Discord server.
