### ISSUE TITLE
 How do I change the avatar for each bot on the site?

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#168]
Nazeem, How do I change the avatar for each bot on the site?

We wish each bot to have its own customized avatar.

How to customize the display of the human manager's photo for each widget?

**Comment by Shubham5231** [comment]
hello @ferstpetr777  is the github data source is working on your side

**Comment by ferstpetr777** [comment]
Yes, why?

**Comment by Shubham5231** [comment]
in my side its not working

**Comment by Shubham5231** [comment]
rest of thing are working properly.

**Comment by Shubham5231** [comment]
which version ur  using?

**Comment by n4ze3m** [comment]
> We wish each bot to have its own customized avatar.

Currently, you can't customize the avatar directly, but can you update the script code in this file: https://github.com/n4ze3m/dialoqbase/blob/main/app/script/src/svg.ts#L1

**Comment by n4ze3m** [comment]
Hey, there's a new release for the embedding script editor! Users can now easily add a custom avatar or icon and change the default color directly from the application. I'm closing this issue; feel free to reopen it if you encounter any errors

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/7c5db810-7f25-49d1-a9a0-cf85d6b2f76e)
