### ISSUE TITLE
prisma error

### ISSUE THREAD

**Issue by Shubham5231** [n4ze3m/dialoqbase#169]
we get this error while we run server 
![image](https://github.com/n4ze3m/dialoqbase/assets/141299278/d9b637d2-92d4-4d6a-b5ab-894e17357330)

**Comment by n4ze3m** [comment]
Hey, the error is occurring because the BotSource data is deleted while processing in the queue

**Comment by Shubham5231** [comment]
@n4ze3m  Hey okey, then what we do now ? because this error occurring all the time.

**Comment by n4ze3m** [comment]
Are you using PostgreSQL locally or on any cloud service?

**Comment by Shubham5231** [comment]
@n4ze3m  we are using a supabase postgreSQL.

**Comment by Shubham5231** [comment]
@n4ze3m   we have chagnes db and migrate data again still occuring same error

**Comment by Shubham5231** [comment]
@n4ze3m  locally we are using supabase but on server we use server local posgresql db

**Comment by n4ze3m** [comment]
Did you guys use the same Redis URL for both the server and local? If so, please don't use it, as it may cause conflict issues

**Comment by Shubham5231** [comment]
@n4ze3m  r we don't use same url we are using server pc's local redis url
