### ISSUE TITLE
Getting error while we ask a question to chatbot.

### ISSUE THREAD

**Issue by Shubham5231** [n4ze3m/dialoqbase#170]
![image](https://github.com/n4ze3m/dialoqbase/assets/141299278/b2de190a-b126-402d-b788-f737b5f3410d)

**Comment by Shubham5231** [comment]
@n4ze3m  can u check it out this issue plz

**Comment by n4ze3m** [comment]
Hey, are you using OpenAI embeddings? Is this error still occurring?

**Comment by Shubham5231** [comment]
yes we are using openAI  emededdings and aslo this error still  occurring

**Comment by Shubham5231** [comment]
@n4ze3m  when i use model is GPT-3.5 turbo(OpenAI) and emededdings  is text-emededding-ada-002 we use

**Comment by n4ze3m** [comment]
Please verify that the OpenAI API key is working, as it may be the cause of the issue.

**Comment by Shubham5231** [comment]
@n4ze3m okey

**Comment by Shubham5231** [comment]
@n4ze3m can plz tell me the which Chat Model we are use and Embedding model we use ? we need stable version so please

**Comment by n4ze3m** [comment]
I can't recommend a specific model. Usually, I chat with the X application using OpenAI models

**Comment by Shubham5231** [comment]
@n4ze3m  can  u look at this error because i try with latested version 4.6.
![image](https://github.com/n4ze3m/dialoqbase/assets/141299278/1f67d284-addc-4337-b007-5706dd7f92b9)

**Comment by n4ze3m** [comment]
I will look into it. I tested it yesterday, but I can't reproduce the error.

**Comment by Shubham5231** [comment]
@n4ze3m  okey ,
plz resolve this issue
