### ISSUE TITLE
Chatbot API

### ISSUE THREAD

**Issue by JombleContact** [n4ze3m/dialoqbase#173]
Hello,

It would be awesome if you could add the API for file upload / deletion

**Comment by n4ze3m** [comment]
Hey, I don't understand what type of file upload you're referring to. Currently you can upload  files as a data source?

**Comment by JombleContact** [comment]
Datasources for me are dynamic, and the folder of the datasource is dynamic.
It would be a good purpose to implement just a upload / deletion files but via API so it can be automated (script done of the side of the user for sure).

Example : I upload some files on my folder, my python script is analyzing when I upload or delete datasources and then it fetch the API (see this: https://docs.chaindesk.ai/api-reference/endpoint/datasources/create)

**Comment by aiconauser98** [comment]
+1

**Comment by n4ze3m** [comment]
Nice, I will try the upcoming release.

**Comment by n4ze3m** [comment]
Hey, Dialoqbase API and SDK are now released.

Go to Settings > Profile > Create API Key, then use it as the Authorization key.

You can access Swagger docs by visiting {your_dialoqbase_url}/docs.

SDK Documentation (not fully completed): https://dialoqbase.n4ze3m.com/reference/getting-started.html

If you face any issue, please join Dialoqbase Discord server.
