### ISSUE TITLE
[QUESTION] - Developer mode

### ISSUE THREAD

**Issue by olaronymax** [n4ze3m/dialoqbase#175]
Hello, I would like to contribute to the project, but I had some problems deploying in development mode, could you provide a step-by-step guide to run in development mode?

**Comment by n4ze3m** [comment]
Hey, thank you for your interest in contributing.

You can check out local development details here:  https://dialoqbase.n4ze3m.com/guide/running-locally-for-development.html

(which is a bit old, so you don't need to do everything).

You need Redis and Postgres with pgvector, that's all.

Here's a simple guide:

1. Clone the repo.
2. Use pnpm to install dependencies for the frontend (`pnpm i` and `pnpm dev` to start the frontend server).
3. CD into the server, use yarn (or pnpm), ensure you've added all required environment variables, and run `yarn`  and `yarn dev`

That's it!

The frontend will run on 5123, and the backend will run on 3000.
