### ISSUE TITLE
Chat widget overflow on mobile

### ISSUE THREAD

**Issue by nsollazzo** [n4ze3m/dialoqbase#176]
Hello, i noticed that the chat widget is not quite responsive on mobile since it goes over the edges of the screen

**Comment by n4ze3m** [comment]
Yes, the widget is not responsive with the mobile layout now. It is fixed and will be released in the next update

**Comment by n4ze3m** [comment]
I'm closing this as a fix has been released. If it is still encountered, please reopen it. Thanks
