### ISSUE TITLE
Sending voice messages via Telegram system does not automatically determine the language

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#180]
Nazeem, Greetings, when sending voice messages via Telegram system does not automatically determine the language and always perceive the message only in English, then responds only in English, and the response does not correspond to the request. Please help with the solution of the problem thank you very much.

**Comment by ferstpetr777** [comment]
And it seems to be the same problem when we add a link for recognition to the YouTube knowledge base

**Comment by n4ze3m** [comment]
Hey, thanks for reporting. I will update the whisper to detect actual language instead of just English.

**Comment by comeback01** [comment]
You need to define this in the prompt system, there's nothing to change in the code to make it work, and don't forget that all the models are multilingual.

**Comment by mahimairaja** [comment]
Makes sence @comeback01
