### ISSUE TITLE
Can not fetch Ollama

### ISSUE THREAD

**Issue by PyT1m** [n4ze3m/dialoqbase#186]
Hello, I'm unable to fetch the Ollama model. It is running and I'm using your provided URL as you can see in the picture.
Maybe you can help me with my problem. Thank you :)
![error 1](https://github.com/n4ze3m/dialoqbase/assets/155635615/152bd840-e8a3-4cb7-ba0c-1e6ae4be732b)
![error 2](https://github.com/n4ze3m/dialoqbase/assets/155635615/07337a4a-3e20-4cf4-a8a7-b5b54fd4df54)

**Comment by n4ze3m** [comment]
Interesting, I will look into it. 🤔 Are you using Windows?

**Comment by wrapss** [comment]
> Hello, I'm unable to fetch the Ollama model. It is running and I'm using your provided URL as you can see in the picture. Maybe you can help me with my problem. Thank you :) ![error 1](https://private-user-images.githubusercontent.com/155635615/294166970-152bd840-e8a3-4cb7-ba0c-1e6ae4be732b.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzE3NjEsIm5iZiI6MTcwNDM3MTQ2MSwicGF0aCI6Ii8xNTU2MzU2MTUvMjk0MTY2OTcwLTE1MmJkODQwLWU4YTMtNGNiNy1iYTBjLTFlNmFlNGJlNzMyYi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMjMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODkwOTc3NTU4NWE2YzgwNzFmZjY2ZTFmOGU4ZjZkZTdkMWY3OGNiMzIwZTE2Y2NmYWRkOWU2OTI0ZmU2OGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2nuBaTcZJ6xt77LBDPoVINmIyQUR_wRE7s0_0KekOlk) ![error 2](https://private-user-images.githubusercontent.com/155635615/294166977-07337a4a-3e20-4cf4-a8a7-b5b54fd4df54.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzE3NjEsIm5iZiI6MTcwNDM3MTQ2MSwicGF0aCI6Ii8xNTU2MzU2MTUvMjk0MTY2OTc3LTA3MzM3YTRhLTNlMjAtNGNmNC1hOGE3LWI1YjU0ZmQ0ZGY1NC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMjMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjNhM2ZhOTI5YmUwY2RiNzY5ZjU5MGY2NjNhZjc5YTA0ODJiNTk1MmEzNjVjZjVjNTdiMGEyNjRhN2UwMTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sV7L26k7p5KdHhpjcP-NP86WfjwfxUcN1lLboBsx4So)

if you run ollama with OLLAMA_HOST=0.0.0.0, you can use the local ipv4 of your computer

**Comment by PyT1m** [comment]
I'm using ubuntu 22.04. The local ipv4 isn't working and produces the same result

**Comment by n4ze3m** [comment]
Hey, this might be a helpful solution for you, I guess.
https://stackoverflow.com/a/4354173

**Comment by n4ze3m** [comment]
Hey, I'm closing this issue. Feel free to reopen it if you still have any problems. I've upgraded the way to add Ollama models in the latest version. Also, if you're looking for a simple Ollama web UI, you can try out https://pageassist.n4ze3m.com/. It doesn't require Docker or anything, just a simple Chrome extension.
