### ISSUE TITLE
Problems after update to 1.7

### ISSUE THREAD

**Issue by phpia** [n4ze3m/dialoqbase#196]
Hi! Is necessary any change in the configuration or similar after update 1.7?

Im not able to get working any bot.

Thanks

**Comment by n4ze3m** [comment]
Hey, what error is the application throwing? There is no configuration required.

**Comment by n4ze3m** [comment]
Hey, which embedding model are you using?

**Comment by n4ze3m** [comment]
Hey, If you are not using Docker, go to the server folder and run `yarn seed`

**Comment by phpia** [comment]
Yes, Im not using Docker

yarn seed, fix the problem
:)

Thanks!
