### ISSUE TITLE
How to delete.

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#197]
Hello,

There are several things I want to delete, but I can't:

1) users
2) Messages in the playground

Thanks for your help

**Comment by n4ze3m** [comment]
Hey, there is no way to do it currently, but it will be added in the next update (1.7.1)

**Comment by n4ze3m** [comment]
Hey, you need to upgrade to the latest version (1.11.3) in order to use the delete feature

![image](https://github.com/user-attachments/assets/47362f1a-d9fe-46a5-8a0c-cae511505f43)
