### ISSUE TITLE
context window to 16K

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#204]
Nazim hi! can you please tell me if there is a way to increase the context window to 16K in fireworks model Mixtral MoE 8x7B Instruct/ just 4000 is not enough for message capture of large texts.

**Comment by n4ze3m** [comment]
Hey, does Fireworks' `Mixtral MoE 8x7B Instruct` have a 16K context?

**Comment by n4ze3m** [comment]
Currently, they only have a 4000-context length.

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/40784cdd-227f-437a-ab6a-5d2d779dc638)

**Comment by ferstpetr777** [comment]
The model itself has this feature. Here's a screenshot from their official website. https://mistral.ai/news/mixtral-of-experts/
<img width="1440" alt="Снимок экрана 2024-01-26 в 20 21 05" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/f23eb3e1-3bb9-4737-9c28-eebf6f2523ba">

**Comment by ferstpetr777** [comment]
If there will be a context window in the context of 32k tokens, as stated in the model, then GPT is no longer needed, on tests this model shows the best results. With the right knowledge base and instructions. All that is needed is a large context window. Your tool dialog base is the best!

**Comment by ferstpetr777** [comment]
Nazim has a question.   How to add to dialogbase   MISTRAL_API_KEY https://docs.mistral.ai/ ?

**Comment by n4ze3m** [comment]
The Mistral API is OpenAI-compatible. To proceed, navigate to the models section in settings and click on add new model button and paste the following URL: `https://api.mistral.ai/v1`, along with your API key.

**Comment by ferstpetr777** [comment]
Nazim respect! I did everything according to the instructions, but the connection did not work). something went wrong).....

**Comment by n4ze3m** [comment]
What error did you get?

**Comment by ferstpetr777** [comment]
there is a very large log ), please try it yourself when you have time, it's very complicated ...

**Comment by ferstpetr777** [comment]
the whole log is at the google doc link https://docs.google.com/document/d/1iAsWInJdkFVGZ1o4MkcDsIZE2eW5rKtm8cszlghtfIY/edit?usp=sharing
