### ISSUE TITLE
suggestion: To make the Bot chat ui similar to the playground

### ISSUE THREAD

**Issue by xubairp** [n4ze3m/dialoqbase#205]
Hello Nazeem,

 Amazing project and thanks for sharing.

 I have suggestion to make the bot interface similar to playground. looks like playground is alot better in terms of providing the source and also the markdown visuals.
 
 sample visual are attached:
 
 
using the playground: 
![image](https://github.com/n4ze3m/dialoqbase/assets/128311411/fcf417b7-043e-44a6-a725-06e16a5a2d63)

using the bot interface:
![image](https://github.com/n4ze3m/dialoqbase/assets/128311411/cb107d94-bd32-4015-bcee-1ef6154eb504)

**Comment by n4ze3m** [comment]
Hey, thank you for the suggestions. I'm planning to introduce a new sharable link, similar to the Playground UI

**Comment by xubairp** [comment]
Hey @n4ze3m , amazing work with the 1.7.7 just loving it. i hope you can consider this for the next release

**Comment by n4ze3m** [comment]
Hey, Dialoqbase API and SDK are now released.

Go to Settings > Profile > Create API Key, then use it as the Authorization key.

You can access Swagger docs by visiting {your_dialoqbase_url}/docs.

SDK Documentation (not fully completed): https://dialoqbase.n4ze3m.com/reference/getting-started.html

If you face any issue, please join Dialoqbase Discord server.
