### ISSUE TITLE
How to Set Up Nginx with Let's Encrypt SSL for Docker Containers on Debian and AlmaLinux

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#207]
Hello everyone,

I'd like to share with you a step-by-step guide on setting up Nginx with Let's Encrypt SSL certificates for Docker containers on both Debian and AlmaLinux 9.1 systems. The process is quite similar for both operating systems, but there are some minor differences in the commands used.

**For AlmaLinux:**

1. **DNS Configuration:**
   Ensure each domain points to your VPS IP address using an A record in your domain provider's DNS settings.

2. **Install Nginx:**
   ```
   sudo dnf install nginx
   ```

3. **Start and Enable Nginx:**
   ```
   sudo systemctl start nginx
   sudo systemctl enable nginx
   ```

4. **Install Certbot and the Nginx plugin:**
   ```
   sudo dnf install certbot python3-certbot-nginx
   ```

5. **Create Nginx Server Blocks:**
   Create a `.conf` file for each domain in `/etc/nginx/conf.d/` and configure it with the server block using the `proxy_pass` directive pointing to your Docker container.
   ```
   sudo nano /etc/nginx/conf.d/yourdomain.com.conf
   ```

6. **Test and Reload Nginx Configuration:**
   ```
   sudo nginx -t
   sudo systemctl reload nginx
   ```

7. **Obtain and Install SSL Certificates:**
   Run Certbot for each domain.
   ```
   sudo certbot --nginx -d yourdomain.com
   ```
   If automatic installation fails, install the certificate manually with:
   ```
   sudo certbot install --cert-name yourdomain.com
   ```

8. **Verify Automatic Renewal:**
   Check if a cron job or systemd timer has been created for certificate renewal.
   ```
   sudo systemctl list-timers | grep certbot
   # or
   cat /etc/crontab | grep certbot
   ```

9. **Test HTTPS on your Sites:**
   Visit `https://yourdomain.com` to ensure the certificate is correctly installed and the site is secure.

10. **Repeat for Additional Domains / Containers.**

**For Debian:**

1. Follow steps 1 and 5-10 from the AlmaLinux instructions. The main difference is in the installation of Nginx and Certbot:

2. **Install Nginx:**
   ```
   sudo apt update
   sudo apt install nginx
   ```

3. **Start and Enable Nginx:**
   ```
   sudo systemctl start nginx
   sudo systemctl enable nginx
   ```

4. **Install Certbot and the Nginx plugin:**
   ```
   sudo apt install certbot python3-certbot-nginx
   ```

By following these steps, you should be able to configure Nginx with SSL for your Docker containers on both AlmaLinux  and Debian systems. Remember to replace `yourdomain.com` with your actual domain name and adjust the `proxy_pass` to your container's port. Also, ensure the configuration files are correct for your setup, and always backup your configurations before making changes.

Feel free to ask any questions or share your experiences!

**Comment by n4ze3m** [comment]
Hey, thank you. You don't need to set up SSL if your domain is with Cloudflare; they offer it for free.

**Comment by comeback01** [comment]
The advantage of this system is that there is no longer a port 3000, but a direct access to the domain.

In this way, you can have multiple containers on different ports (3001, 3002, 14000, etc).

Each container will have its domain name, its SSL certificate, on port 80.
