### ISSUE TITLE
please suggest a method or library statistics of traffic usage of chat bots

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#209]
Hi Nazim, please suggest a method or library, framework format or library on git that can be used to implement in the personal profile of the service dalogbase user statistics of chat bots, statistics of traffic usage of chat bots, and the ability to accept payments for a given traffic. Thank you very much in advance!

**Comment by n4ze3m** [comment]
Hey, sorry about it. I haven't had time to look into Dialoqbase currently, which is why there are so many pending feature implementations.

If you are looking for a BI tool, I suggest going for Metabase. It is open source and can be self-hosted (https://www.metabase.com/), allowing you to generate reports and statistics.

**Comment by ferstpetr777** [comment]
Nazim, good evening! I have connected the statistics meta database. please tell me in which tables to look for data for graphing statistics of the use of AI models token volume by bots ? thank you for the answer! 
<img width="1035" alt="Снимок экрана 2024-02-11 в 20 37 16" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/728d5cf4-5884-4fdc-9a5b-b1d3928401dc">

**Comment by ferstpetr777** [comment]
loaded as a service into docker, all tables appeared ! ) , but the question of where to find data for statistics chat bots has become even wider!) Nazim, please tell me where to look? 
<img width="1172" alt="Снимок экрана 2024-02-12 в 00 55 44" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/b2607747-779c-482f-aaba-5c43d7ff55ed">
<img width="1171" alt="Снимок экрана 2024-02-12 в 00 55 35" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/38ffd73d-d307-4dcb-8c35-03103bd98f89">
<img width="1185" alt="Снимок экрана 2024-02-12 в 00 55 21" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/7288379f-47b9-49f0-bbed-8997a314a5f1">
