### ISSUE TITLE
Error - replicate,  model mistralai/mixtral-8x7b-instruct-v0.1

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#214]
Nazim, help me please! What's wrong?  The model is successfully connected to the dialog base, I specify the correct api key, but when I ask in the sandbox - it gives an error :  There was an error processing your request.

Log : 

{ detail: 'The requested resource could not be found.', status: 404 }
ApiError: Request to https://api.replicate.com/v1/models/mistralai/mixtral-8x7b-instruct-v0.1/versions/undefined failed with status 404 Not Found: {"detail":"Not found."}.
    at Replicate.request (/app/node_modules/replicate/index.js:232:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Replicate.getModelVersion (/app/node_modules/replicate/lib/models.js:43:20)
    at async Replicate._call (/app/node_modules/@langchain/community/dist/llms/replicate.cjs:87:29)
    at async Promise.all (index 0)
    at async Replicate._generate (/app/node_modules/@langchain/core/dist/language_models/llms.cjs:322:29)
    at async Replicate._generateUncached (/app/node_modules/@langchain/core/dist/language_models/llms.cjs:138:22)
    at async Replicate.invoke (/app/node_modules/@langchain/core/dist/language_models/llms.cjs:32:24)
    at async Replicate._streamIterator (/app/node_modules/@langchain/core/dist/language_models/llms.cjs:49:13)
    at async Replicate.transform (/app/node_modules/@langchain/core/dist/runnables/base.cjs:343:9) {
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'GET',
      localURLsOnly: false,
      unsafeRequest: false,
      body: null,
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 404,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Found',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by n4ze3m** [comment]
Hey, I know this issue.  Currently, you need to mention the version of the Replicate model (langchain issue), which will be addressed in the upcoming update.

You can currently fix this by mentioning the version of the model:

```
mistralai/mixtral-8x7b-instruct-v0.1:7b3212fbaf88310cfef07a061ce94224e82efc8403c26fc67e8f6c065de51f21
```

**Comment by ferstpetr777** [comment]
Super ! Thank you very much ! it worked !  You're the best!
