### ISSUE TITLE
OpenRouter support for language and embedding models 

### ISSUE THREAD

**Issue by brinrbc** [n4ze3m/dialoqbase#217]
> Hey! v1.3.0 has been released, which allows you to easily add OpenRouter models. Simply go to Settings > Model > Add New Model.
> Base URL: https://openrouter.ai/api/v1 API Key: OpenRouter API key
> Select the model you want to add.
> Please note that currently, we only support chat models

Could you please tell me if you have removed the Add Model function? I can't find it in the Settings > Model >

**Comment by n4ze3m** [comment]
I will add it in the next update, which is already planned.

**Comment by GarrettG-AI** [comment]
was this ever completed?  I don't see embedding models in the model lists or in API docs?

**Comment by CHesketh76** [comment]
I don't see embedding models still.

**Comment by j-zhrv** [comment]
@n4ze3m Please help us understand how to use embedding models with the OpenRouter API key.

**Comment by heather-jones** [comment]
Is this available or not? Still can't find any docs for it.

**Comment by n4ze3m** [comment]
Hey guys, OpenRouter does not support embedding models. I'm sorry for any confusion. They only support chat models according to their docs

![Image](https://github.com/user-attachments/assets/9549b593-f8f7-4c0e-b1a9-167b96f32775)

**Comment by NoorChasib** [comment]
what was the reason for not supporting embedding models? Just curious if it's a technical issue or something else? Seemed like everything was good to go earlier in feb!

**Comment by yasinBursali** [comment]
why in the world you wouldnt support embedding models? im using openrouter to simplify my project and not having thousands of environment variables for api credentials etc. i want to spend my money as a developer but ure not accepting it lol

**Comment by n4ze3m** [comment]
Hey , OpenRouter still doesn't support embeddings yet. If they do, I'll add it as an option.

**Comment by namhihi237** [comment]
hmm , yes waitting for embedding for OpenRouter

**Comment by DylPorter** [comment]
Agree, this is a much needed feature and it's even surprising that it doesn't exist yet.

**Comment by Tabod-joshua** [comment]
Please does openrouter produce any embedding services '
