### ISSUE TITLE
Data Source stuck at pending state (source type: Website)

### ISSUE THREAD

**Issue by adurhmn-aeq** [n4ze3m/dialoqbase#218]
When adding new data source, or when creating a bot, the data source gets stuck in the "Pending" state. This happens randomly and cannot figure out the cause. Is this a known issue? How to get around this?

Note: I verified that my redis db is running without any issues.

![21419e16-9d37-4e92-b79a-75ea778500ff](https://github.com/n4ze3m/dialoqbase/assets/113497521/dd63338f-499c-41a8-bd89-ab9f6d1fc224)

**Comment by n4ze3m** [comment]
Since there is no issue with Redis, I think the source you entered may have an issue. I suggest restarting the application; this might resolve it. Also, which embedding model are you using?

**Comment by brinrbc** [comment]
> When adding new data source, or when creating a bot, the data source gets stuck in the "Pending" state. This happens randomly and cannot figure out the cause. Is this a known issue? How to get around this?
> 
> Note: I verified that my redis db is running without any issues.
> 
> ![21419e16-9d37-4e92-b79a-75ea778500ff](https://private-user-images.githubusercontent.com/113497521/305929457-dd63338f-499c-41a8-bd89-ab9f6d1fc224.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTIzNDQsIm5iZiI6MTcwODM1MjA0NCwicGF0aCI6Ii8xMTM0OTc1MjEvMzA1OTI5NDU3LWRkNjMzMzhmLTQ5OWMtNDFhOC1iZDg5LWFiOWY2ZDFmYzIyNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTQxNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU2MDA3NDhjNzhiMTlkNzJlMDc0NDNiOGEyYjNhZjVhNjhmOGRlNTdkYWY1MGZhZmQwODM4NDRmN2IzNGJmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1VxbMEOpCdmGFc1LQ7NI9O-DbZMugPythrYTzlkAHIE)

try to load the database locally-text for example or a file. two possible reasons are a weak internet connection (VPN?) or check the API key of the model selected for embedding, in playground for example.
