### ISSUE TITLE
No createdAt - HELP!

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#219]
Nazim, good day ! In the Database, in the fields of message tables: telegram, discord and watsapp there are no createdAt timestamps.  Please add it ! Without createdAt data it is impossible to set up statistics of bots usage correctly.

**Comment by n4ze3m** [comment]
I will add it in upcoming updates.

**Comment by ferstpetr777** [comment]
Nazim, can you please tell me when this opportunity will be available?

**Comment by ferstpetr777** [comment]
Nazim, thank you so much! You are the best developer on github !

**Comment by ferstpetr777** [comment]
Nazim good day ! Could you please tell me in which table the history of bot's messages is saved when there is a connection via bot's API ?
<img width="1077" alt="Снимок экрана 2024-02-24 в 17 16 29" src="https://github.com/n4ze3m/dialoqbase/assets/133219575/d48fecd3-333a-4068-979a-3059404c7ced">
