### ISSUE TITLE
Question - api bot message statistics

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/dialoqbase#223]
Nazim good day ! Could you please tell me in which table the history of bot's messages is saved when there is a connection via bot's API ?

**Comment by n4ze3m** [comment]
Hey, unfortunately, the current API request is not being saved in a table

**Comment by PeterBusalov** [comment]
Nazim Greetings! please tell me, maybe you have an idea how to analyze API activity to count bot tokens ?

**Comment by n4ze3m** [comment]
You can add a check in the API handler for counting tokens. You can use the 'js-tiktoken' package

**Comment by PeterBusalov** [comment]
Nazim Afternoon! You know the code of this project very well. Can you please tell me the logic, how can you make it possible to intercept all incoming and outgoing messages to AI models by API open ai? To record them into a database for statistics.

**Comment by n4ze3m** [comment]
Hey, I have added a new table for the API integration, similar to other integrations.

**Comment by PeterBusalov** [comment]
Great! Thank you ! as soon as we do all the statistics I will report back how we organized everything , as a basis we took meta base , it was suitable as a universal ready api gjl connectable to docker databases
