### ISSUE TITLE
Commands telegram

### ISSUE THREAD

**Issue by senavi888** [n4ze3m/dialoqbase#225]
Hello! The built-in telegram bot has the commands /clear and /ping
Can you tell me what the bot sends to the service if this integration is done through the API? I'm just making my own telegram bot and I can't understand it.
Thank you!

**Comment by n4ze3m** [comment]
I don't quite understand your question, but if you're creating a Telegram bot, I highly recommend using https://grammy.dev/ for it. For command cases in Dialoqbase https://github.com/n4ze3m/dialoqbase/blob/893ab797ccf706ef533b136730b2cd1dc9024db7/server/src/integration/telegram.ts#L33
I set them using the `bot.api.setMyCommands` API offered by the Grammy library. However, you can also set commands via Telegram's BotFather."

**Comment by senavi888** [comment]
The your native telegram bot has a command /clean 
What command should I send for this function when I integrate through your API Integration in dialoqbase?

**Comment by n4ze3m** [comment]
The 'clear' command means it will remove existing chat memory from the bot's conversation. You can edit it here:

https://github.com/n4ze3m/dialoqbase/blob/893ab797ccf706ef533b136730b2cd1dc9024db7/server/src/integration/telegram.ts#L48

**Comment by n4ze3m** [comment]
There is no API on Dialoqbase for Telegram; everything is managed by Dialoqbase itself. However, for Discord, I think you can set custom commands.

**Comment by senavi888** [comment]
Thanks a lot! I owe you coffee.

**Comment by n4ze3m** [comment]
Haha, thanks! Feel free to ask questions anytime. No need to buy coffee every time. 😜
