### ISSUE TITLE
YouTube Transcript Support

### ISSUE THREAD

**Issue by mjtechguy** [n4ze3m/dialoqbase#229]
I really love the feature in the tool to pull YT videos down and then transcribe them and add them to the vector DB, but it can take a long time especially with very long videos.

Would it be possible to pull the transcripts directly from Youtube if they are available? This would speed it up significantly.

This tool appears to do it that way: https://chromewebstore.google.com/detail/youtube-summary-with-chat/nmmicjeknamkfloonkhhcjmomieiodli

Thanks!

**Comment by n4ze3m** [comment]
Yes, I already planned for it, and it will be added in the next release. :)

**Comment by mjtechguy** [comment]
Of course you did! Haha. You are always ahead of the game. Thank you!

**Comment by n4ze3m** [comment]
Hey, v1.7.6 has been released, and YouTube transcripts are now supported. However, there is a drawback: it won't work with age-restricted videos for now. We will fix this in upcoming updates

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/9046267b-fac6-4b19-b9b8-f30e62710396)

**Comment by n4ze3m** [comment]
Hey @mjtechguy , Now Page Assist also lets you chat with the YouTube

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/0190cbbd-74a8-4d80-99cb-25b33e32865a)

**Comment by mjtechguy** [comment]
Works perfectly! Thank you!
