### ISSUE TITLE
How to update working setup

### ISSUE THREAD

**Issue by senavi888** [n4ze3m/dialoqbase#234]
Hello! I couldn’t find instructions on how to properly update a working installation. So as not to lose data. Tell me please?

**Comment by senavi888** [comment]
Sorry i found:)))
docker-compose pull

**Comment by n4ze3m** [comment]
Haha, don't worry. There are docs available for updating to the latest version at https://dialoqbase.n4ze3m.com/guide/upgrading-local.html. And don't worry about data loss; all updates merged to the main branch undergo manual testing by me before publishing them :)
