### ISSUE TITLE
 please check your plan and billing details.

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#235]
Hello,

I want to put Word files, and I get this error message, but I don't understand why.

I have no problem with OpenAI and my other applications.

Thanks for the help

`dialoqbase           | No pending migrations to apply.
dialoqbase           | Running seed command `ts-node prisma/seed.ts` ...
dialoqbase           | Seeding new models...
dialoqbase           |
dialoqbase           | 🌱  The seed command has been executed.
dialoqbase           | [info] use ffmpeg.wasm v0.12.0
dialoqbase           | Connecting to database...
dialoqbase           | [info] use ffmpeg.wasm v0.12.0
dialoqbase           | Processing queue
dialoqbase           | loading docx
dialoqbase           | Error [InsufficientQuotaError]: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
dialoqbase           |     at Object.defaultFailedAttemptHandler [as onFailedAttempt] (/app/node_modules/@langchain/core/dist/utils/async_caller.cjs:39:21)
dialoqbase           |     at RetryOperation._fn (/app/node_modules/p-retry/index.js:67:20)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           | Processing queue
dialoqbase           | loading docx
dialoqbase           | Error [InsufficientQuotaError]: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
dialoqbase           |     at Object.defaultFailedAttemptHandler [as onFailedAttempt] (/app/node_modules/@langchain/core/dist/utils/async_caller.cjs:39:21)
dialoqbase           |     at RetryOperation._fn (/app/node_modules/p-retry/index.js:67:20)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           | Processing queue
dialoqbase           | loading docx
dialoqbase           | Error [InsufficientQuotaError]: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
dialoqbase           |     at Object.defaultFailedAttemptHandler [as onFailedAttempt] (/app/node_modules/@langchain/core/dist/utils/async_caller.cjs:39:21)
dialoqbase           |     at RetryOperation._fn (/app/node_modules/p-retry/index.js:67:20)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           | Processing queue
dialoqbase           | loading docx
dialoqbase           | Error [InsufficientQuotaError]: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
dialoqbase           |     at Object.defaultFailedAttemptHandler [as onFailedAttempt] (/app/node_modules/@langchain/core/dist/utils/async_caller.cjs:39:21)
dialoqbase           |     at RetryOperation._fn (/app/node_modules/p-retry/index.js:67:20)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 please check your plan and billing details.dialoqbase-postgres  | 2024-03-11 17:15:56.694 UTC [27] LOG:  checkpoint starting: time
dialoqbase-postgres  | 2024-03-11 17:15:57.591 UTC [27] LOG:  checkpoint complete: wrote 10 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.845 s, sync=0.020 s, total=0.897 s; sync files=11, longest=0.010 s, average=0`

**Comment by n4ze3m** [comment]
Hello, as you can see, this error is related to OpenAI: `Error [InsufficientQuotaError]: 429 You exceeded your current quota. Please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.` It seems there's an issue with your usage quota
