### ISSUE TITLE
HTTP 404 while adding custom embedding model

### ISSUE THREAD

**Issue by tbhaxor** [n4ze3m/dialoqbase#236]
When I am adding custom embedding model, it is giving me 404 error. Even though I have selected the **OpenAI Compatible API** in the first option, it is still sending ollama in the request.

![image](https://github.com/n4ze3m/dialoqbase/assets/28386721/2f553eb5-c966-496a-a8d8-7fcb62dd913e)

This is the curl request I copied from the network request. 

```sh
curl 'https://REDACTED/api/v1/admin/models/fetch' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.7' \
  -H 'Authorization: REDACTED' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: sessionId=REDACTED; db_token=REDACTED' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-GPC: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"ollama_url":"http://REDACTED/v1","api_type":"ollama"}'
```

> [!NOTE]
> 
> `http://REDACTED/v1` is where my **OpenAI Compatible API** is running.

**Comment by n4ze3m** [comment]
Hey, thank you for pointing out that there was an issue on the frontend. We will release a fix later today

**Comment by tbhaxor** [comment]
@n4ze3m I see the code is fixed but you re-opened the issue. Should I test now or wait?

**Comment by tbhaxor** [comment]
Yes it is working.
