### ISSUE TITLE
dialoqbase api

### ISSUE THREAD

**Issue by hkjang** [n4ze3m/dialoqbase#238]
It would be nice if dialoqbase all function could be called using API. thank you

**Comment by n4ze3m** [comment]
Hey, Dialoqbase API and SDK are now released.

Go to Settings > Profile > Create API Key, then use it as the Authorization key.

You can access Swagger docs by visiting {your_dialoqbase_url}/docs.

SDK Documentation (not fully completed): https://dialoqbase.n4ze3m.com/reference/getting-started.html

If you face any issue, please join Dialoqbase Discord server.

**Comment by hkjang** [comment]
oh super fast. thanks @n4ze3m 
but some error on docs path

![image](https://github.com/n4ze3m/dialoqbase/assets/3069493/fcd12b85-e0f1-4fd1-9749-a3a6eeab105f)

**Comment by n4ze3m** [comment]
Oh, sorry, I think it's not working on the production build. I guess it will be resolved in the next update

**Comment by FarazPatankar** [comment]
Hey, came across Dialoqbase via the Railway template. Has this issue been fixed since? The docs should probably also be updated to reflect the presence of an API.

**Comment by n4ze3m** [comment]
Yes, it's fixed. The current version of /docs is working fine.

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/a59b7f36-ad02-451a-bf67-5047bf0852df)
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/04d3694e-a43f-4d2e-bc99-efde3a8f8622)
