### ISSUE TITLE
Docx error

### ISSUE THREAD

**Issue by Antazia** [n4ze3m/dialoqbase#24]
Error: Corrupted zip: can't find end of central directory
﻿at ZipEntries.readEndOfCentral (/app/node_modules/jszip/lib/zipEntries.js:170:23)
﻿at /app/node_modules/jszip/lib/load.js:48:24

When docx are too large, getting error.

**Comment by n4ze3m** [comment]
Oh no 😓, the data loader can't load large files. I have the same issue with PDF files as well https://github.com/n4ze3m/dialoqbase/issues/24. I think I need to try unstructured.io for file loading

**Comment by Antazia** [comment]
Sorry I would like to help, but I'm not able to develop.
I'm struggling with trying to separate chatbots for each account but can't manage to do it so you can see how newbie I am

**Comment by n4ze3m** [comment]
> Sorry I would like to help, but I'm not able to develop. I'm struggling with trying to separate chatbots for each account but can't manage to do it so you can see how newbie I am

It's okay. What is the approx size of the file you tried ?

**Comment by Antazia** [comment]
15Mb, also you can only upload one per one, it's not really convenient.

Just trying to help to improve, not complaining btw !

**Comment by Antazia** [comment]
++ can I get a one line explanation or where I should search to separate chatbots depending user?

**Comment by n4ze3m** [comment]
> 15Mb, also you can only upload one per one, it's not really convenient.
> 
> Just trying to help to improve, not complaining btw !

Dialoqbase is still in the early stage and not fully stable. However, multiple file uploading will be allowed in upcoming updates.

**Comment by n4ze3m** [comment]
> ++ can I get a one line explanation or where I should search to separate chatbots depending user?

Could you please provide more details?   Is it related to Dialoqbase bot 😅😅?

**Comment by Antazia** [comment]
I think it is related, so I created a new user in the supabase database. But when I login into a new user, every chatbots created by other users are shared and accessible

**Comment by n4ze3m** [comment]
> I think it is related, so I created a new user in the supabase database. But when I login into a new user, every chatbots created by other users are shared and accessible

Did you deploy using Railway? If so, did you change the username and password?

**Comment by Antazia** [comment]
I did: please look here : https://dialoqbase-server-production-8132.up.railway.app/

I created 2 accounts : 
login: 
pw: admin
/
login: demo
pw: admin
But when you create a chatbot on one account, the other account also have it.

**Comment by n4ze3m** [comment]
>  But when you create a chatbot on one account, the other account also have it.

Deleting this comment because credentials have been exposed.

**Comment by n4ze3m** [comment]
Sorry, I initially created Dialoqbase with a single user point of view. I will  add support for multiple users on upcoming release :)

**Comment by Antazia** [comment]
I've also added you on Linkedin. 
I'd like to talk to you in more detail about your project and have a few questions.

In any case, thank you for your communication and your help !

**Comment by n4ze3m** [comment]
> Sorry, I initially created Dialoqbase with a single user point of view. I will add support for multiple users on upcoming release :)



Hey, changing the entire codebase of the Dialoqbase main repo is not possible, as it may cause issues. So, I've decided to create a separate repo and set up multiple authentication methods using Supabase.

You can find the repo here: https://github.com/n4ze3m/dialoqbase-multi-user

Additionally, here's a small documentation guide: https://dialoqbase.n4ze3m.com/guide/transitioning-from-single-user-to-multi-user-mode.html
