### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by djav1985** [n4ze3m/dialoqbase#281]
I see in change log you added new GitHub loader. What is the exact change? is it more capable of larger repos? if so any rough deal what it can handle?

**Comment by n4ze3m** [comment]
Yes, the current one can handle a larger repo. I tested it on [MinIO Docs](https://github.com/minio/docs) with around 700+ files. It may take some time to create the embeddings.

For the embedding model, I tested Nomic via Ollama and text-ada embedding from OpenAI. I do not recommend using all-minilm for larger repo

**Comment by djav1985** [comment]
What about the two newer text embedding models the small and large one from open AI?

**Comment by n4ze3m** [comment]
It will work fine, I mean, in case you want to use an embedding model running locally
