### ISSUE TITLE
No documentation found : Embedding settings & more

### ISSUE THREAD

**Issue by wiwatoms** [n4ze3m/dialoqbase#38]
First: It's a really great project. Compared to many other comparable chatbot projects I like the clean interface, the customization y the useful additional features like the integrations and the very easy installation! 

Maybe you can help me:
1. Where / how can I change the a) amount and b) the length of context chunks from the embeddings?
2. Can I customize the welcome message?
3. After ~10 sources I couldn't add more. Is it on purpose?

Would be great to hearing from you! Keep up the good work!

**Comment by n4ze3m** [comment]
hey

> Where / how can I change the a) amount and b) the length of context chunks from the embeddings?

Currently, there is no way to change the length of context through the UI. The only way to change it is by modifying the code

>  length of context chunks from the embeddings?

I'm working on a new update this weekend where you can customize the chatbox UI :)

> After ~10 sources I couldn't add more. Is it on purpose?

Yes, uploading a huge amount of files at once may slow down the system/server. To upload additional batches, you can go to the data source page

**Comment by wiwatoms** [comment]
Hey @n4ze3m,

Thanks for your quick feedback!

1) In other repos I could identify the files to change this code. Could you direct me where I have to make the changes manually? For my use cases the standard settings are not going very well.
2. Great!
3. What I've meant: I uploaded the sources already in the data sources page file by file until it completed. I seemed to hit the limit of the general uploads with about 10 items in the source page list. If I add one more file it gets ignored and nothing shows up anymore. I restarted the docker environment, but it didn't fix it so far.

**Comment by n4ze3m** [comment]
hey, 

> 1. In other repos I could identify the files to change this code. Could you direct me where I have to make the changes manually? For my use cases the standard settings are not going very well.

Sure, You can change the embedding data source loaders chunk size from the  `server/src/queue/controller/ ` folder 

for example:

https://github.com/n4ze3m/dialoqbase/blob/79e8fe0184882d0d3e45c37feef07ebe8f847530/server/src/queue/controllers/pdf.controller.ts#L18


> 3. What I've meant: I uploaded the sources already in the data sources page file by file until it completed. I seemed to hit the limit of the general uploads with about 10 items in the source page list. If I add one more file it gets ignored and nothing shows up anymore. I restarted the docker environment, but it didn't fix it so far.

I think there may be a bug in the code. I will check locally. 🙃

Btw you can change the file upload count from the code by modifying these two files'.

https://github.com/n4ze3m/dialoqbase/blob/79e8fe0184882d0d3e45c37feef07ebe8f847530/app/ui/src/components/Common/BotForm.tsx#L106

https://github.com/n4ze3m/dialoqbase/blob/79e8fe0184882d0d3e45c37feef07ebe8f847530/server/src/app.ts#L20

**Comment by wiwatoms** [comment]
Incredible, thank you so much for your assistance! 

A) If I get it right: Those settings define the size of the chunks (of a pdf or a website) when it gets stored into the vector database. If it's loaded into the GPT context window, I have no control over the chunk size. It always loads one or more chunks of 1000? I have no control over the length of the chunk that gets loaded in my context window? 
B) Where I can change the amount of chunks getting loaded into the context window? Right now I have the impression it's very small. For my use case I would like to load rather more, but smaller chunks and use the new GPT3.5 with larger context window.

I hope my terminology is clear enough to understand.

Gabweal idea: So far not a single chatbot here on github I've found really gives you UI access to those settings. I think those are really elemental to make the chabot work out for different use cases. Giving people control in an advanced settings tab would really differentiate this repo from others. Then the community can much better experiment what is good for optimizing the experience and later offering maybe something like templates for different use cases.

**Comment by n4ze3m** [comment]
> A) If I get it right: Those settings define the size of the chunks (of a pdf or a website) when it gets stored into the vector database. If it's loaded into the GPT context window, I have no control over the chunk size. It always loads one or more chunks of 1000? I have no control over the length of the chunk that gets loaded in my context window?

yeh :/

> B) Where I can change the amount of chunks getting loaded into the context window? Right now I have the impression it's very small. For my use case I would like to load rather more, but smaller chunks and use the new GPT3.5 with larger context window.

tbh, I have no idea about that. I'm currently using Langchain's [ConversationalRetrievalQA ](https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval) and need to check their documentation for more customizations details :/-.

Btw starting from **v0.0.14**, you can customize the chatbox greeting message, bot name, chat bubble colors, etc. :)

**Comment by n4ze3m** [comment]
Closing this issue. If you encounter any issues, feel free to reopen it. Thank you
