### ISSUE TITLE
PDF import fails.

### ISSUE THREAD

**Issue by cidrugHug8** [n4ze3m/dialoqbase#4]
Hi,
The following error was output to the docker log.
```
loading pdf
Warning: Indexing all PDF objects
Error
    at InvalidPDFExceptionClosure (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:452:35)
    at Object.<anonymous> (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:455:2)
    at __w_pdfjs_require__ (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at Object.<anonymous> (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:7939:23)
    at __w_pdfjs_require__ (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at /app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:88:18
    at /app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:91:10
    at webpackUniversalModuleDefinition (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:18:20)
    at Object.<anonymous> (/app/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:25:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  message: 'Invalid PDF structure'
}
```

**Comment by n4ze3m** [comment]
Hi there, I'm sorry for the PDF loading issue you encountered. Could you please confirm whether you used a signed PDF file? This information will help me better understand the problem and provide you with the appropriate solution. Thank you!

**Comment by n4ze3m** [comment]
UPDATE: I tested with a password-protected PDF file, and it failed to process. I will figure out how to resolve this issue.

**Comment by cidrugHug8** [comment]
Thank you for your quick reply. PDF file is not encrypted. pdfinfo results are as follows
```
$ pdfinfo  Engineer\ Reference.pdf 
Title:           My Document
Subject:         
Keywords:        
Author:          yamada
Producer:        madbuild
CreationDate:    Wed Jun 22 11:02:51 2022 JST
ModDate:         Wed Jun 22 11:02:51 2022 JST
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           175
Encrypted:       no
Page size:       595.28 x 841.89 pts (A4)
Page rot:        0
File size:       25883386 bytes
Optimized:       no
PDF version:     1.4
```

**Comment by noureldinz3r0** [comment]
same
i get this error:
PDF.js v2.9.359 (build: e667c8cbc)
Message: Invalid PDF structure.

but not all pdfs, if the pdf is a bit large this happens

**Comment by n4ze3m** [comment]
> same i get this error: PDF.js v2.9.359 (build: e667c8cbc) Message: Invalid PDF structure.
> 
> but not all pdfs, if the pdf is a bit large this happens

Yes, I am currently using pdf-parse as a document loader, but it cannot handle large files. So, I am trying to set up a custom loader that will split large PDFs into smaller ones and then feed them to pdf-parse.

**Comment by n4ze3m** [comment]
Hey guys, I have created a custom [PDF loader](https://github.com/n4ze3m/dialoqbase/blob/v0.0.12/server/src/loader/pdf.ts ) on v0.0.12. I hope it resolves the issue with large PDF files.  Please try the latest version and let me know.


_Note that the PDF loader still can't load protected PDF files._

**Comment by l4time** [comment]
I'm able to upload PDFs with thousand of pages with v0.0.12. Fixed it for me

**Comment by n4ze3m** [comment]
Closing this issue based on the comment above. Feel free to reopen if the problem still exists. Thank you.
