### ISSUE TITLE
Contribution help

### ISSUE THREAD

**Issue by ChristophePRAT** [n4ze3m/dialoqbase#46]
It would be great to have precise instructions on how one can contribute to this project.
I would like to add more data loaders, but don't know how I can run this project locally, without pulling an image.

It appears that building and running this repo after each change is not a good way to proceed. Can someone tell me which commands I should run in order to be able to make changes?
I am on macOS and have tried running `yard install`, and `yarn build`, but when I do that, I can see the login page but the XMLHttpRequest fails (404 error).

Thanks in advance for any help!

**Comment by n4ze3m** [comment]
Hey, thank you for showing interest in contributing. I will add documentation on how to run it locally, including the required environments, either later today or tomorrow.

**Comment by n4ze3m** [comment]
Dialoqbase is a monorepo, but due to some issues with `pnpm`, I moved the server separately and started using `yarn`

A 404 issue usually indicates that the frontend is unable to connect with the backend URL. You need to add the following to the `app/ui` environment file:


```env
VITE_API_URL=http://localhost:3000/api/v1
VITE_HOST_URL=http://localhost:3000
```
do the same for the `app/widget`:

```env
VITE_API_URL=http://localhost:3000/bot
```

**Comment by ChristophePRAT** [comment]
Hi! I have finally managed to run the app locally. I am not sure that I did it the right way, so please let me know if these steps are correct.
1. Rename `app/ui/.env.example` to `app/ui/.env` as you mentioned
2. Rename `app/widget/.env.example` to `app/widget/.env` as you mentioned
3. Install `redis` (on macOS, you can use `brew install redis`), and run `redis-server`
4. Rename `server/.env.example` to `server/.env` and fill in the environment variables such that:
- `DATABASE_URL` is the URL of the PostgreSQL database that can be found in Supabase here:
<img width="1470" alt="Screenshot 2023-06-29 at 21 08 26" src="https://github.com/n4ze3m/dialoqbase/assets/22614130/ffe0833b-6a78-498a-9ead-2290c1a81362">

- `DB_REDIS_URL` is `redis://localhost:6379` (please change the port to the port that was printed when running `redis-server`)
- `OPENAI_API_KEY` is the OpenAI API key
- `DB_SECRET_KEY` is the JWT secret token that can be found on Supabase in the API section (⚠️ this is a wild guess; I'm really unsure that it was the correct secret)
5. Run `yarn install` in the main folder and in the `server` folder
6. Run `yarn dev` in the main folder
7. Run `yarn dev:start` in the `server` folder

Let me know if I missed something (which I probably did). Thanks a lot for the clue! 

After you give me some feedback, I will do a pull request for `README.md` to add documentation about the local installation.

**Comment by n4ze3m** [comment]
Yes, it's correct. Sorry for making it hard to set up for local development.

For running the server, I recommend using `yarn dev` instead of `yarn dev:start`.

Also, you don't need to install Redis on your PC. You can use free Redis from Upstash or Railway for development.

`DB_SECRET_KEY` is not from Supabase, btw. I think I made it a little confusing in that part of the self-hosting section 😁😅😅 . It is used for JWT token generation for local authentication.

**Comment by n4ze3m** [comment]
> After you give me some feedback, I will do a pull request for README.md to add documentation about the local installation.

I suggest creating a new file called `CONTRIBUTION.md` and adding instructions there.

**Comment by ChristophePRAT** [comment]
> DB_SECRET_KEY is not from Supabase, btw. I think I made it a little confusing in that part of the self-hosting section 😁😅😅 . It is used for JWT token generation for local authentication.

Where can should I get it from, then? Or maybe you meant that it is not specific to Supabase but I used the correct token?

**Comment by n4ze3m** [comment]
> Where can should I get it from, then? Or maybe you meant that it is not specific to Supabase but I used the correct token? Or is it a random key?

Random key

**Comment by ChristophePRAT** [comment]
Thanks! I now get the error `{"message":"Route GET:/bot/437993b5-caf4-47ef-bc20-87cafd460120?mode=iframe&no=button not found","error":"Not Found","statusCode":404}` inside an `iframe` when I try to use a bot (`http://localhost:5173/#/bot/cljifowrz0000h1f1ce53uvfi`). Have I done something wrong with the configuration, or should I open a new issue?

**Comment by n4ze3m** [comment]
That's because the server is unable to find the widget build, so we need to manually build it and move it to the server's distribution folder using the following commands:

* Comment out the 'app/ui' and 'app/widget' environment variables in the `.env` files.

* Run the command  `pnpm build`. This will build both the UI and widget.

* Move the 'dist' folder to the server's distribution folder:

```bash
mv app/ui/dist server/dist/public
```

* Next, move the widget files:

```bash
mv app/widget/dist/index.html server/dist/public/bot.html
```

```bash
cp -r app/widget/dist/assets/*  server/dist/public/assets/  
```

**Comment by n4ze3m** [comment]
I am closing this issue. If you encounter any issues, feel free to reopen it. Thank you

**Comment by ken-kuro** [comment]
> Dialoqbase is a monorepo, but due to some issues with `pnpm`, I moved the server separately and started using `yarn`
> 
> A 404 issue usually indicates that the frontend is unable to connect with the backend URL. You need to add the following to the `app/ui` environment file:
> 
> ```dotenv
> VITE_API_URL=http://localhost:3000/api/v1
> VITE_HOST_URL=http://localhost:3000
> ```
> 
> do the same for the `app/widget`:
> 
> ```dotenv
> VITE_API_URL=http://localhost:3000/bot
> ```

Sorry for bringing this up again after a long time, but I wonder what "some issues" you were talking about?

**Comment by n4ze3m** [comment]
> Sorry for bringing this up again after a long time, but I wonder what "some issues" you were talking about?

idk what really happened after installing the fastify plugins the server application started acting strangely, throwing random errors. That's why I moved the server out of the app and used `yarn`

maybe because of the  `pnpm` version I used
