### ISSUE TITLE
The current answer speed is too slow, can you help optimize it to use streaming output to improve user experience

### ISSUE THREAD

**Issue by stupidboy12138** [n4ze3m/dialoqbase#49]
The current answer speed is too slow, can you help optimize it to use streaming output to improve user experience
![image](https://github.com/n4ze3m/dialoqbase/assets/32326223/55c80951-819a-411c-a4e5-a4f98810be9f)

**Comment by stupidboy12138** [comment]
I like this project very much, but I know how to use TypeScript to develop, I think the streaming output of openAi answer results will greatly improve the user experience, please help me

**Comment by n4ze3m** [comment]
Yeah, I will add streaming support. Currently, streaming support is limited to some LLMs, which is why I didn't add it at the beginning.

**Comment by stupidboy12138** [comment]
> Yeah, I will add streaming support. Currently, streaming support is limited to some LLMs, which is why I didn't add it at the beginning.

Thank you very much.I want to know when this change will be updated to the project. I think this stream can greatly improve the user experience. It is very important. I hope to use it quickly.

**Comment by n4ze3m** [comment]
Maybe this weekend or next, since I'm a little busy right now with work and other personal stuff. I will keep this issue open and let you know

**Comment by stupidboy12138** [comment]
> Maybe this weekend or next, since I'm a little busy right now with work and other personal stuff. I will keep this issue open and let you know

thank you very much you are so nice

**Comment by n4ze3m** [comment]
Hey, streaming support will come with this weekend's update.

![Streaming Example](https://i.imgur.com/SHZ8NHP.gif)

**Comment by n4ze3m** [comment]
Hey, I just published [v0.0.18](https://github.com/n4ze3m/dialoqbase/tree/v0.0.18), which supports streaming. To enable streaming (by default, it's in normal mode because some LLMs do not support streaming yet), go to the bot settings and toggle the streaming option. I will close this issue if you encounter any errors. Feel free to reopen it.

**Comment by stupidboy12138** [comment]
> Hey, I just published [v0.0.18](https://github.com/n4ze3m/dialoqbase/tree/v0.0.18), which supports streaming. To enable streaming (by default, it's in normal mode because some LLMs do not support streaming yet), go to the bot settings and toggle the streaming option. I will close this issue if you encounter any errors. Feel free to reopen it.

thank you very much
