### ISSUE TITLE
Github issue

### ISSUE THREAD

**Issue by kevinseabourne** [n4ze3m/dialoqbase#57]
I am not able to connect the github repo it says status failed

**Comment by kevinseabourne** [comment]
no its public, I was getting a 401 server error in the console, trying to chat also

**Comment by n4ze3m** [comment]
Hmm, interesting. Did you provide the GitHub access token as an environmental variable?

**Comment by n4ze3m** [comment]
Already have a few issues with GitHub loader https://github.com/n4ze3m/dialoqbase/issues/37

**Comment by kevinseabourne** [comment]
yes provided in the .env file

**Comment by n4ze3m** [comment]
Ok, I will check what happened and update here when the fix is released.

**Comment by n4ze3m** [comment]
Hey, just released v0.0.20 with a custom GitHub loader that clones the repo locally instead of using the GitHub API. It also supports private repos by providing an access token, similar to the GitHub API. Let me know if you face any issues.

**Comment by kevinseabourne** [comment]
This error must not be github related, as I saw the data in the terminal, but you still cannot chat with the AI
![Screenshot 2023-07-22 at 4 50 52 pm](https://github.com/n4ze3m/dialoqbase/assets/29522030/801f7ca0-e236-413f-8f1b-47e8022e18aa)



![Screenshot 2023-07-22 at 4 48 31 pm](https://github.com/n4ze3m/dialoqbase/assets/29522030/f043dd55-f61a-4019-936c-3bb16380be0d)


and 
![Screenshot 2023-07-22 at 4 37 12 pm](https://github.com/n4ze3m/dialoqbase/assets/29522030/eebc49c2-799d-494e-8277-b36e57bfaf7e)

**Comment by n4ze3m** [comment]
Hmm, it's an internal server error :/ No error on the terminal?

**Comment by kevinseabourne** [comment]
that error was my bad, I provided the wrong openAI API. But when trying to chat about a public repo I provided the ai responded 

`
context provided is not in a readable format. Please provide the context in a clear and understandable format so I can assist you better
`

I like your decision to just clone the repo, Im not sure how your scrapping the repo locally. I tried to do something like this, using a python algo to scrape a Github repo and post each file to a single text file along with the file name and directory that file came from. I then uploaded that to chatGPT and it worked it out. Also you scrapper seems only scrape websites that allow it, I just tried to talk to the AI about an article on a website, I provided and this did not work it sighted legal reason from the site preventing it. 

If you can get the plugins working and allow users to choose 20 max per bot or something, this will sort of solve the problem scrapping any website as some of the plugins can do that. The dream for me is to have a deep conversation about a repo you provide, then provide it links to the latest code documentation for a language to read and even have a plugin that transcribes youtube videos and a code interpreter plugin. What you have built so far is absolutely awesome dude and the fact that it is open source, shows how much of a good person you are !  

Also when you add or remove data sources the chat history is gone, if you can prevent this that would be great !

**Comment by n4ze3m** [comment]
just used 'git clone' and read all files using 'fs.' You can check the code here : https://github.com/n4ze3m/dialoqbase/blob/main/server/src/loader/github.ts

**Comment by n4ze3m** [comment]
> If you can get the plugins working and allow users to choose 20 max per bot or something, this will sort of solve the problem scrapping any website as some of the plugins can do that.

I will look into how to set up plugins / agents for dialoqbase :)

**Comment by n4ze3m** [comment]
> Also when you add or remove data sources the chat history is gone, if you can prevent this that would be great !

The current playground is just an iframe from bot sharable URL. I already planned to improve the playground UI with a history feature, similar to that of ChatGPT UI. However, I got busy with personal stuff, so I will try to add it in the upcoming release :)

**Comment by n4ze3m** [comment]
> context provided is not in a readable format. Please provide the context in a clear and understandable format so I can assist you better

Try changing the prompt and temperature, and also consider trying the 16k context model 👀
