### ISSUE TITLE
Can't Preview or Use Playground for Chatbot

### ISSUE THREAD

**Issue by AbrahimZaman360** [n4ze3m/dialoqbase#59]
I am unable to use the playground and preview the bot

**Comment by AbrahimZaman360** [comment]
Getting Following Error/Log in Iframe:
{"message":"Route GET:/bot/d9f98fac-cc35-4357-a2c5-ea8cd619074a?mode=iframe&no=button not found","error":"Not Found","statusCode":404}

**Comment by n4ze3m** [comment]
Hey, sorry for the issue. Is it running on a railway or Docker?

**Comment by AbrahimZaman360** [comment]
When I Build on Docker I get error

**Comment by AbrahimZaman360** [comment]
I'm using local system node for frontend and docker for redis and postgres

**Comment by AbrahimZaman360** [comment]
Everything Works fine Except for this

**Comment by AbrahimZaman360** [comment]
I am unable to build the server because I'm getting error in docker envirnoment

**Comment by n4ze3m** [comment]
Oh, okay. That's because of the missing 'widget' folder on the server. Can you please check this documentation: https://github.com/n4ze3m/dialoqbase/blob/main/CONTRIBUTION.md
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/573eabce-feb2-4062-bbb6-20c2262fe10d)

**Comment by n4ze3m** [comment]
step 3, 4 and 5

**Comment by AbrahimZaman360** [comment]
Thanks Dude! I try it now

**Comment by AbrahimZaman360** [comment]
> Oh, okay. That's because of the missing 'widget' folder on the server. Can you please check this documentation: https://github.com/n4ze3m/dialoqbase/blob/main/CONTRIBUTION.md ![image](https://user-images.githubusercontent.com/39720973/255251074-573eabce-feb2-4062-bbb6-20c2262fe10d.png)

Add it in Docs Folder

**Comment by n4ze3m** [comment]
sure :)

**Comment by AbrahimZaman360** [comment]
> sure :)

In Main Directory Should I use Pnpm or Yarn?

**Comment by AbrahimZaman360** [comment]
Because I see pnpm-lock.yaml there!

**Comment by n4ze3m** [comment]
Use pnpm for the root and Yarn for the server 😁

**Comment by AbrahimZaman360** [comment]
I think we're using old Prisma client ? "prisma": "^4.15.0"

**Comment by AbrahimZaman360** [comment]
Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

**Comment by n4ze3m** [comment]
Nah, I have already migrated to Prisma 5 on the next branch . It will merge into the main branch this weekend

https://github.com/n4ze3m/dialoqbase/blob/93f87e8273eccf0e7675e2cfeb53f58546367671/server/package.json#L68

**Comment by AbrahimZaman360** [comment]
Great!! Okay Can You tell me about saving chat history?

**Comment by AbrahimZaman360** [comment]
Bro You're Great Developer Kasm Se (:+1:

**Comment by n4ze3m** [comment]
Currently, chat history is only being saved for Telegram and Discord integration

**Comment by AbrahimZaman360** [comment]
I'm trying to create a new route for the conversation hub where are chat will be stored with actions like delete and copy.

**Comment by n4ze3m** [comment]
If you want to save web chat history, you can use this [hook](https://github.com/n4ze3m/dialoqbase/blob/main/app/widget/src/hooks/useChatId.tsx). Generate a unique user ID, send it to the server, and create a similar table as in Telegram/Discord integration

**Comment by AbrahimZaman360** [comment]
Thanks I Hope Our Chat will Help Someone! 
There is Currently No Option of Using Hugging Face Large Models Stuck at Embeddings Only!

**Comment by n4ze3m** [comment]
For using HF or other open-source LLMs locally, it needs to run in a Python environment. I have some plans to create a Python backend server that utilizes open-source models and can be easily integrated with an existing Node.js server through simple inner API calls.

The main limitations will be that it might be slow or require a huge amount of RAM/GPU. It won't run on railway (mostly).

**Comment by AbrahimZaman360** [comment]
No About HF Models in Cloud via API

**Comment by AbrahimZaman360** [comment]
You did in Embeddings but Not For LLM.
I've tried in Langchain and I got Output on Embeddings via HF Interfernce API

**Comment by n4ze3m** [comment]
> No About HF Models in Cloud via API

Oh, okay, it is actually easy with Langchain, I guess.

https://js.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_inference

**Comment by n4ze3m** [comment]
Hey, closing this issue. If you encounter any issues, feel free to reopen it :)

**Comment by AbrahimZaman360** [comment]
> Hey, closing this issue. If you encounter any issues, feel free to reopen it :)

Which OS You're Using Now Right Now?
I want to use the same so i don't get errors.

**Comment by n4ze3m** [comment]
Windows 11

**Comment by AbrahimZaman360** [comment]
> Windows 11 

Wsl?

**Comment by AbrahimZaman360** [comment]
> Windows 11 

Last thing Does it support multiple users? Or Just 1

**Comment by n4ze3m** [comment]
Just 1 for now.

**Comment by n4ze3m** [comment]
If you want multiple user support, use Supabase Auth and update the JWT plugin code :)

**Comment by n4ze3m** [comment]
I have already received a few requests regarding multiple user support. As an internal project (not open source), I've already implemented multiple user support using Supabase Auth on dialoqbase. I will write a docs about it next week

**Comment by AbrahimZaman360** [comment]
Can you share that project (: 😹

**Comment by AbrahimZaman360** [comment]
> Can you share that project (: 😹
> 

Can I Get that If Possible?
Thanks I've to Upload it in Cloud of Mine.

**Comment by n4ze3m** [comment]
Yes, I'll create a forked repository with multiple users on the weekend :)

**Comment by AbrahimZaman360** [comment]
Great 😃

Ibrahim Zaman,
Software Developer (Mid) n DevOps Engineer (Junior)

Web Link:
https://abrahimzaman.com
________________________________
