### ISSUE TITLE
Multi user?

### ISSUE THREAD

**Issue by rossman22590** [n4ze3m/dialoqbase#63]
Can users have their own bots via supabase?

**Comment by n4ze3m** [comment]
Hey, I created dialoqbase from a single-user point of view, but I received many requests for multi-user auth . It's challenging to change the entire code base, but I will create a forked repo that implements multi-user auth and write detailed documentation for it

**Comment by rossman22590** [comment]
sounds amazing!

**Comment by AbrahimZaman360** [comment]
@n4ze3m  waiting for forked repo haha

**Comment by n4ze3m** [comment]
Hey, changing the entire codebase of the Dialoqbase main repo is not possible, as it may cause issues. So, I've decided to create a separate repo and set up multiple authentication methods using Supabase. 

You can find the repo here: https://github.com/n4ze3m/dialoqbase-multi-user

Additionally, here's a small documentation guide: https://dialoqbase.n4ze3m.com/guide/transitioning-from-single-user-to-multi-user-mode.html
