### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [n4ze3m/dialoqbase#72]
Dear dialoqbase developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by n4ze3m** [comment]
oh great, I will look into it thanks for the suggestion
