### ISSUE TITLE
website data source issue

### ISSUE THREAD

**Issue by n4ze3m** [n4ze3m/dialoqbase#76]
i always get data source failed on whatever website link i put in, any ideas?

_Originally posted by @TommyWong92 in https://github.com/n4ze3m/dialoqbase/discussions/1#discussioncomment-6973772_

**Comment by TommyWong92** [comment]
![image](https://github.com/n4ze3m/dialoqbase/assets/106639301/0223315d-6279-4b42-9195-3403857d8a0b)
seem like langchain exceed quota

**Comment by n4ze3m** [comment]
Oh, I think it's an OpenAI error. Can you try another embedding model like TensorFlow or all-MiniLM-L6-v2 with any data source?

**Comment by TommyWong92** [comment]
![image](https://github.com/n4ze3m/dialoqbase/assets/106639301/b7d31074-8add-412d-8372-4409c0dbed08)
 HI, i have using OpenAI to source pdf, but somehow i notice it work on small pdf only. when i upload large pdf, it will killed the process.
is it problem from the railway server doesn't support?

2. i have uploaded multi pdf, but when i ask something in 2nd pdf it told me no answer from 1st pdf. is this the queue management issue?

**Comment by n4ze3m** [comment]
Yeah, there was an issue related to PDFs a few months ago, but it was solved. What size of PDF did you try? Maybe it's because of railway's limited memory.

**Comment by TommyWong92** [comment]
10mb size pdf which is the tesla manual pdf
https://www.tesla.com/ownersmanual/2017_2023_model3/en_eu/Owners_Manual.pdf

**Comment by n4ze3m** [comment]
I think it's a railways issue; it works on my local PC.

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/2e83fa9c-d1a2-4d9d-896e-5dc8e5c51125)
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/4799b19b-4798-40db-8f6a-bf4af2816e27)
![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/817174a3-45b6-4119-9f39-27e758f9f30c)
