### ISSUE TITLE
FST_JWT_AUTHORIZATION_TOKEN_INVALID

### ISSUE THREAD

**Issue by phpia** [n4ze3m/dialoqbase#80]
Hi, Im following the steps for local installation, I want to be able to contribute to the project :)

But Im getting FST_JWT_AUTHORIZATION_TOKEN_INVALID, when trying to access to http://localhost:3000/api/v1/bot

Some help?

Thanks

**Comment by phpia** [comment]
Sorry not an issue, you must go first to /login so next calls to API works

**Comment by n4ze3m** [comment]
> I want to be able to contribute to the project :)

wow thanks <3

>  Sorry not an issue, you must go first to /login so next calls to API works


no problem

**Comment by n4ze3m** [comment]
🥹Hey, thank you for sponsoring!!! Do you want any features or enhancements? Are you using Dialoqbase?
