### ISSUE TITLE
ENHANCEMENT: Decouple content processing from UI

### ISSUE THREAD

**Issue by mjtechguy** [n4ze3m/dialoqbase#91]
Right now, if I load a bunch of material in, specifically long running tasks like mp3, mp4 or YouTube videos, the Web UI hangs.

 
![image](https://github.com/n4ze3m/dialoqbase/assets/29070994/a8d84770-e3c0-4dc3-b0aa-0c146c847b49)

Being able to scale out the 'workers' separately from the web-ui in a queue / scale out type system would be great. The queue is sending back a processing notification to the web-ui, and someone could continue to load resources in, and then they take a long to process as they take, but the UI is still available.

Does this make sense? Let me know if I am talking crazy.

**Comment by n4ze3m** [comment]
Yes, I also noticed that issue when using the YouTube loader.

Anyway ;) I already separated the process on the v1.0.0 branch, as seen here https://github.com/n4ze3m/dialoqbase/blob/5b917a42cee2c647a1ce47fef1b874b16ea1481b/server/src/plugins/bull.ts#L22 
This is based on the Bull Queues docs https://github.com/OptimalBits/bull#separate-processes

**Comment by mjtechguy** [comment]
Awesome sir. You are already ahead of it. Thank you!
