### ISSUE TITLE
Stuck at "Bot is cooking...  It may take some time"

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#95]
I had no problem creating new bots on the 0.0.3 version , but on the 1.0.0 Version , i get stuck at "Bot is cooking...  It may take some time" , noting that i tired using all-Mini and OpenAI embedding models and its the same issue .

**Comment by n4ze3m** [comment]
Are you running the application locally or on railway.app ?

**Comment by n4ze3m** [comment]
Hey, sorry, but it looks like a migration issue :/ `q_13`. The only way to fix this is by deleting the existing PostgreSQL folder and Redis, and then restarting the server:

```
sudo rm -rf .redis
sudo rm -rf .postgres
```

**Comment by n4ze3m** [comment]
Idk why your PostgreSQL database has a migration issue since all my new changes won't cause any issues to the existing database. I will look into it

**Comment by oalmajalists** [comment]
root@PD-OMARMJ:~/dialoqbase/docker# sudo rm -rf .redis
root@PD-OMARMJ:~/dialoqbase/docker# sudo rm -rf .postgres
root@PD-OMARMJ:~/dialoqbase/docker# sudo docker-compose up
Starting redis               ... done
Starting dialoqbase-postgres ... done
Starting dialoqbase          ... done
Attaching to dialoqbase-postgres, redis, dialoqbase
dialoqbase-postgres | The files belonging to this database system will be owned by user "postgres".
dialoqbase-postgres | This user must also own the server process.
dialoqbase-postgres |
dialoqbase-postgres | The database cluster will be initialized with locale "en_US.utf8".
dialoqbase-postgres | The default database encoding has accordingly been set to "UTF8".
dialoqbase-postgres | The default text search configuration will be set to "english".
dialoqbase-postgres |
dialoqbase-postgres | Data page checksums are disabled.
dialoqbase-postgres |
redis            | 1:C 03 Oct 2023 11:32:22.980 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis            | 1:C 03 Oct 2023 11:32:22.980 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis            | 1:C 03 Oct 2023 11:32:22.980 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis            | 1:C 03 Oct 2023 11:32:22.980 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dialoqbase-postgres | fixing permissions on existing directory /var/lib/postgresql/data ... ok
redis            | 1:M 03 Oct 2023 11:32:22.980 * monotonic clock: POSIX clock_gettime
dialoqbase-postgres | creating subdirectories ... ok
dialoqbase-postgres | selecting dynamic shared memory implementation ... posix
dialoqbase-postgres | selecting default max_connections ... 100
redis            | 1:M 03 Oct 2023 11:32:22.981 * Running mode=standalone, port=6379.
dialoqbase-postgres | selecting default shared_buffers ... 128MB
dialoqbase-postgres | selecting default time zone ... Etc/UTC
redis            | 1:M 03 Oct 2023 11:32:22.981 * Server initialized
redis            | 1:M 03 Oct 2023 11:32:22.981 * Ready to accept connections tcp
dialoqbase-postgres | creating configuration files ... ok
dialoqbase-postgres | running bootstrap script ... ok
dialoqbase-postgres | performing post-bootstrap initialization ... ok
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase-postgres | syncing data to disk ... ok
dialoqbase-postgres |
dialoqbase-postgres |
dialoqbase-postgres | Success. You can now start the database server using:
dialoqbase-postgres |
dialoqbase-postgres |     pg_ctl -D /var/lib/postgresql/data -l logfile start
dialoqbase-postgres |
dialoqbase-postgres | initdb: warning: enabling "trust" authentication for local connections
dialoqbase-postgres | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
dialoqbase-postgres | waiting for server to start....2023-10-03 11:32:23.616 UTC [49] LOG:  starting PostgreSQL 15.4 (Debian 15.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
dialoqbase-postgres | 2023-10-03 11:32:23.620 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dialoqbase-postgres | 2023-10-03 11:32:23.629 UTC [52] LOG:  database system was shut down at 2023-10-03 11:32:23 UTC
dialoqbase-postgres | 2023-10-03 11:32:23.634 UTC [49] LOG:  database system is ready to accept connections
dialoqbase-postgres |  done
dialoqbase-postgres | server started
dialoqbase-postgres | CREATE DATABASE
dialoqbase-postgres |
dialoqbase-postgres |
dialoqbase-postgres | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
dialoqbase-postgres |
dialoqbase-postgres | waiting for server to shut down...2023-10-03 11:32:23.795 UTC [49] LOG:  received fast shutdown request
dialoqbase-postgres | .2023-10-03 11:32:23.799 UTC [49] LOG:  aborting any active transactions
dialoqbase-postgres | 2023-10-03 11:32:23.801 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
dialoqbase-postgres | 2023-10-03 11:32:23.801 UTC [50] LOG:  shutting down
dialoqbase-postgres | 2023-10-03 11:32:23.804 UTC [50] LOG:  checkpoint starting: shutdown immediate
dialoqbase-postgres | 2023-10-03 11:32:23.888 UTC [50] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.013 s, sync=0.065 s, total=0.088 s; sync files=301, longest=0.026 s, average=0.001 s; distance=4223 kB, estimate=4223 kB
dialoqbase-postgres | 2023-10-03 11:32:23.893 UTC [49] LOG:  database system is shut down
dialoqbase-postgres |  done
dialoqbase-postgres | server stopped
dialoqbase-postgres |
dialoqbase-postgres | PostgreSQL init process complete; ready for start up.
dialoqbase-postgres |
dialoqbase-postgres | 2023-10-03 11:32:23.914 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
dialoqbase-postgres | 2023-10-03 11:32:23.914 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dialoqbase-postgres | 2023-10-03 11:32:23.914 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dialoqbase-postgres | 2023-10-03 11:32:23.918 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dialoqbase-postgres | 2023-10-03 11:32:23.922 UTC [65] LOG:  database system was shut down at 2023-10-03 11:32:23 UTC
dialoqbase-postgres | 2023-10-03 11:32:23.927 UTC [1] LOG:  database system is ready to accept connections
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase-postgres | 2023-10-03 11:32:24.365 UTC [69] LOG:  could not receive data from client: Connection reset by peer
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Applying migration `init`
dialoqbase       | Applying migration `q_10`
dialoqbase       | Applying migration `q_11`
dialoqbase       | Applying migration `q_12`
dialoqbase       | Applying migration `q_13`
dialoqbase-postgres | 2023-10-03 11:32:24.512 UTC [70] ERROR:  relation "BotTelegramHistory" does not exist
dialoqbase-postgres | 2023-10-03 11:32:24.512 UTC [70] STATEMENT:  -- AlterTable
dialoqbase-postgres |   ALTER TABLE "BotTelegramHistory" ADD COLUMN     "new_chat_id" TEXT;
dialoqbase-postgres |
dialoqbase       | Error: P3018
dialoqbase       |
dialoqbase       | A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
dialoqbase       |
dialoqbase       | Migration name: q_13
dialoqbase       |
dialoqbase       | Database error code: 42P01
dialoqbase       |
dialoqbase       | Database error:
dialoqbase       | ERROR: relation "BotTelegramHistory" does not exist
dialoqbase       |
dialoqbase       | DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"BotTelegramHistory\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("namespace.c"), line: Some(433), routine: Some("RangeVarGetRelidExtended") }
dialoqbase       |
dialoqbase       |
dialoqbase       | error Command failed with exit code 1.
dialoqbase       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase-postgres | 2023-10-03 11:32:26.274 UTC [71] LOG:  could not receive data from client: Connection reset by peer
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Error: P3009
dialoqbase       |
dialoqbase       | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
dialoqbase       | The `q_13` migration started at 2023-10-03 11:32:24.510138 UTC failed
dialoqbase       |
dialoqbase       |
dialoqbase       | error Command failed with exit code 1.
dialoqbase       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dialoqbase exited with code 1
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Error: P3009
dialoqbase       |
dialoqbase       | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
dialoqbase       | The `q_13` migration started at 2023-10-03 11:32:24.510138 UTC failed
dialoqbase       |
dialoqbase       |
dialoqbase       | error Command failed with exit code 1.
dialoqbase       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dialoqbase exited with code 1
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase-postgres | 2023-10-03 11:32:30.060 UTC [75] LOG:  could not receive data from client: Connection reset by peer
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Error: P3009
dialoqbase       |
dialoqbase       | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
dialoqbase       | The `q_13` migration started at 2023-10-03 11:32:24.510138 UTC failed
dialoqbase       |
dialoqbase       |
dialoqbase       | error Command failed with exit code 1.
dialoqbase       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dialoqbase exited with code 1
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Error: P3009
dialoqbase       |
dialoqbase       | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
dialoqbase       | The `q_13` migration started at 2023-10-03 11:32:24.510138 UTC failed
dialoqbase       |
dialoqbase       |
dialoqbase       | error Command failed with exit code 1.
dialoqbase       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dialoqbase exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dialoqbase          ... done
Stopping dialoqbase-postgres ... done
Stopping redis               ... done

**Comment by n4ze3m** [comment]
Hey, I'm releasing a patch now. Sorry for the issue

**Comment by n4ze3m** [comment]
Hey, a patch has been released. Please check if you still encounter the error.

Use the following commands:

```
sudo docker-compose pull
sudo rm -rf .redis
sudo rm -rf .postgres
```
