### ISSUE TITLE
Chat Widget - White Page

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#98]
The bot works well in the playground , but when i get a "Public URL" link from "Integrations" , under "HTML Embed" , the link opens a white empty page .
noting that it used to work under V0.03

**Comment by oalmajalists** [comment]
![image](https://github.com/n4ze3m/dialoqbase/assets/81163928/7ad1d8cc-877a-4ea3-8160-c1c76d5904b0)

**Comment by n4ze3m** [comment]
Hey, idk what your Chrome browser version is, but `crypt.randomUUID()` has been available since Chrome 92. I will add a polyfill to prevent this issue.

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by oalmajalists** [comment]
Tested on , Chrome Version 117.0.5938.150 (Official Build) (64-bit) and Edge Version 117.0.2045.47 (Official build) (64-bit).
Both same error .

**Comment by n4ze3m** [comment]
That's weird. I will add the polyfill later today. Are you using Docker, right?

**Comment by n4ze3m** [comment]
Hey, can you test if the link works for you? This is an instance I hosted on Railway: https://dbclould.up.railway.app/bot/6355f6b0-d9fc-428e-ba6f-1dadf8825c9e

**Comment by oalmajalists** [comment]
The provided link works , and yes i am using docker

**Comment by oalmajalists** [comment]
docker logs below (couldnt find any error in it)

Creating network "docker_default" with the default driver
Creating dialoqbase-postgres ... done
Creating redis               ... done
Creating dialoqbase          ... done
Attaching to redis, dialoqbase-postgres, dialoqbase
dialoqbase-postgres |
dialoqbase-postgres | PostgreSQL Database directory appears to contain a database; Skipping initialization
dialoqbase-postgres |
redis            | 1:C 04 Oct 2023 07:56:33.786 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis            | 1:C 04 Oct 2023 07:56:33.786 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis            | 1:C 04 Oct 2023 07:56:33.786 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis            | 1:C 04 Oct 2023 07:56:33.786 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis            | 1:M 04 Oct 2023 07:56:33.787 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis            | 1:M 04 Oct 2023 07:56:33.787 * monotonic clock: POSIX clock_gettime
redis            | 1:M 04 Oct 2023 07:56:33.791 * Running mode=standalone, port=6379.
redis            | 1:M 04 Oct 2023 07:56:33.791 * Server initialized
redis            | 1:M 04 Oct 2023 07:56:33.799 * Loading RDB produced by version 7.2.1
redis            | 1:M 04 Oct 2023 07:56:33.799 * RDB age 184 seconds
redis            | 1:M 04 Oct 2023 07:56:33.799 * RDB memory usage when created 1.44 Mb
redis            | 1:M 04 Oct 2023 07:56:33.800 * Done loading RDB, keys loaded: 3, keys expired: 1.
redis            | 1:M 04 Oct 2023 07:56:33.800 * DB loaded from disk: 0.009 seconds
redis            | 1:M 04 Oct 2023 07:56:33.800 * Ready to accept connections tcp
dialoqbase-postgres | 2023-10-04 07:56:35.734 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
dialoqbase-postgres | 2023-10-04 07:56:35.743 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dialoqbase-postgres | 2023-10-04 07:56:35.743 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dialoqbase-postgres | 2023-10-04 07:56:35.748 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dialoqbase-postgres | 2023-10-04 07:56:35.762 UTC [29] LOG:  database system was shut down at 2023-10-04 07:53:29 UTC
dialoqbase-postgres | 2023-10-04 07:56:35.964 UTC [1] LOG:  database system is ready to accept connections
dialoqbase       | yarn run v1.22.19
dialoqbase       | $ npx prisma migrate deploy && fastify start  app.js
dialoqbase       | Prisma schema loaded from prisma/schema.prisma
dialoqbase       | Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"
dialoqbase       |
dialoqbase       | 14 migrations found in prisma/migrations
dialoqbase       |
dialoqbase       | Applying migration `q_23`
dialoqbase       |
dialoqbase       | The following migration have been applied:
dialoqbase       |
dialoqbase       | migrations/
dialoqbase       |   └─ q_23/
dialoqbase       |     └─ migration.sql
dialoqbase       |
dialoqbase       | All migrations have been successfully applied.
dialoqbase       | npm notice
dialoqbase       | npm notice New major version of npm available! 9.8.1 -> 10.2.0
dialoqbase       | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
dialoqbase       | npm notice Run `npm install -g npm@10.2.0` to update!
dialoqbase       | npm notice
dialoqbase       | Connecting integration...
dialoqbase       | Connecting to database...
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | history []
dialoqbase       | provider openai
dialoqbase       | modelName gpt-4
dialoqbase       | using openai
dialoqbase       | provider openai
dialoqbase       | modelName gpt-4
dialoqbase       | using openai
dialoqbase       | Waiting for response...
dialoqbase       | clnadgbdx0001la2j7rc6vzqp
dialoqbase       | closed
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase-postgres | 2023-10-04 08:01:35.861 UTC [27] LOG:  checkpoint starting: time
dialoqbase-postgres | 2023-10-04 08:01:38.683 UTC [27] LOG:  checkpoint complete: wrote 30 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.812 s, sync=0.005 s, total=2.822 s; sync files=22, longest=0.002 s, average=0.001 s; distance=57 kB, estimate=57 kB
redis            | 1:M 04 Oct 2023 08:48:15.193 * 100 changes in 300 seconds. Saving...
redis            | 1:M 04 Oct 2023 08:48:15.193 * Background saving started by pid 21
redis            | 21:C 04 Oct 2023 08:48:15.199 * DB saved on disk
redis            | 21:C 04 Oct 2023 08:48:15.199 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis            | 1:M 04 Oct 2023 08:48:15.294 * Background saving terminated with success
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null
dialoqbase       | null

**Comment by n4ze3m** [comment]
I will release a patch tonight. Sorry for the issue.

**Comment by comeback01** [comment]
It works. Thank you.

**Comment by oalmajalists** [comment]
Works great now , and thank you @n4ze3m for your prompt response , your support is exemplary.
