### ISSUE TITLE
fireworks.ai

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#99]
I didn't understand how to use fireworks.ai.

Can you help me?

**Comment by n4ze3m** [comment]
Yes, you can check these docs on how to get an API key from fireworks.ai: https://dialoqbase.n4ze3m.com/guide/ai-providers/fireworks.html#how-to-get-api-key.

**Comment by n4ze3m** [comment]
If you are using it locally, first stop the Docker, then edit the .env file to add the `FIREWORKS_API_KEY` key and its corresponding value, and finally, start the server.

**Comment by comeback01** [comment]
I put in .env:

FIREWORKS_API_KEY="XXXXXXXXXXXXXXXXXX"

In ChatModel, I have for example:

Llama v2 7B (Fireworks).

But in Embedding model

I don't have fireworks.ai.

So it doesn't work.

Thanks for your help

**Comment by n4ze3m** [comment]
Hey, fireworks.ai does not have embedding models at the moment. When they have them, I will add them. Thanks

**Comment by n4ze3m** [comment]
You can use any embedding model with the Fireworks ChatModel on DialoqBase; it will work fine.

**Comment by Shubham5231** [comment]
I didn't understand how to use fireworks.ai. with js

Can you help me?

**Comment by n4ze3m** [comment]
yes, fireworks.ai is similar to OpenAI. They provide APIs for popular open-source models such as Llama, Mistral, and others. On Dialoqbase, you can input your Fireworks API key into the `.env` file and create a bot by selecting Fireworks models from the dropdown menu on the bot creation page
